"""Tests for tack.data.contour: isosurfaces of point data in 3D cells.

The case tables are VTK's (generated by tools/make_contour_tables.py), so
VTK's vtkContourGrid is the reference: every case of every 3D shape, and
real meshes, must give the same triangles with the same orientation.
Without VTK: surfaces are closed, their points are on the isovalue, a
linear field is reproduced, and the structured, rectilinear and explicit
forms of one grid agree.
"""

import types

import numpy as np
import pytest
from test_shapes import EXPECTED

import tack
import tack.data as td
from tack.data import shapes as sh
from tack.runtime.dispatch import env_flag

try:
    from vtkmodules import vtkCommonCore, vtkCommonDataModel, vtkFiltersCore
    from vtkmodules.util.numpy_support import numpy_to_vtk, vtk_to_numpy
except ImportError:
    if env_flag("TACK_REQUIRE_VTK"):
        raise
    vtk = None
else:
    vtk = types.SimpleNamespace(**{name: getattr(module, name)
                                   for module in (vtkCommonCore, vtkCommonDataModel,
                                                  vtkFiltersCore)
                                   for name in dir(module) if name.startswith("vtk")})

needs_vtk = pytest.mark.skipif(vtk is None, reason="needs VTK, the reference")

SOLIDS = [sh.Tetra, sh.Voxel, sh.Hexahedron, sh.Wedge, sh.Pyramid]


def _scalars(values, dtype=tack.f32):
    f = tack.field(dtype, shape=(len(values),))
    f.from_numpy(np.asarray(values).astype(dtype.numpy_dtype))
    return f


def _grid_points(n):
    axis = np.linspace(-1, 1, n)
    return np.array([(x, y, z) for z in axis for y in axis for x in axis])


def _hex_rows(n):
    rows = []
    for k in range(n - 1):
        for j in range(n - 1):
            for i in range(n - 1):
                b = i + j * n + k * n * n
                rows.append([b, b + 1, b + 1 + n, b + n,
                             b + n * n, b + 1 + n * n, b + 1 + n + n * n, b + n + n * n])
    return np.array(rows)


def _sphere(points):
    return np.linalg.norm(points, axis=1)


def _surface(surface):
    return surface.points.to_numpy(vectors=True), surface.cells.connectivity.to_numpy()


def _edges(triangles):
    e = np.sort(np.concatenate([triangles[:, [0, 1]], triangles[:, [1, 2]],
                                triangles[:, [2, 0]]]), axis=1)
    return np.unique(e, axis=0, return_counts=True)[1]


def _oriented(points, triangles, decimals=6):
    """Triangles by coordinates, each rotated to start at its smallest point."""
    out = set()
    for t in triangles:
        c = [tuple(np.round(points[p], decimals)) for p in t]
        s = c.index(min(c))
        out.add(tuple(c[s:] + c[:s]))
    return out


# ── Without a reference ─────────────────────────────────────────────

@pytest.mark.parametrize("form", ["structured", "rectilinear", "explicit"])
def test_a_sphere_is_closed_and_on_the_isovalue(backend, form):
    n = 13
    points = _grid_points(n)
    if form == "structured":
        data = td.DataSet(points, td.StructuredCellSet((n, n, n)))
    elif form == "rectilinear":
        axis = np.linspace(-1, 1, n)
        data = td.rectilinear_grid(axis, axis, axis)
    else:
        data = td.DataSet(points, td.SingleTypeCellSet(sh.Hexahedron, _hex_rows(n)))
    data.point_data["r"] = _scalars(_sphere(points))
    data.point_data["x"] = _scalars(points[:, 0] * 2.0 + 1.0)
    surface = td.contour(data, "r", 0.6)
    pts, triangles = _surface(surface)
    assert len(triangles) > 100
    assert (_edges(triangles) == 2).all()                 # closed: every edge in two triangles
    np.testing.assert_allclose(surface.point_data["r"].to_numpy(), 0.6, atol=1e-6)
    # A field linear in position is interpolated exactly onto the surface.
    np.testing.assert_allclose(surface.point_data["x"].to_numpy(), pts[:, 0] * 2.0 + 1.0,
                               atol=1e-5)
    assert np.linalg.norm(pts, axis=1).max() <= 0.6 + 1e-6


def test_the_three_forms_of_a_grid_agree(backend):
    n = 9
    points = _grid_points(n)
    axis = np.linspace(-1, 1, n)
    forms = [td.DataSet(points, td.StructuredCellSet((n, n, n))),
             td.rectilinear_grid(axis, axis, axis),
             td.DataSet(points, td.SingleTypeCellSet(sh.Hexahedron, _hex_rows(n)))]
    surfaces = []
    for data in forms:
        data.point_data["r"] = _scalars(_sphere(points))
        surfaces.append(_oriented(*_surface(td.contour(data, "r", 0.55)), decimals=5))
    assert surfaces[0] == surfaces[1] == surfaces[2]


def test_merging_points_changes_nothing_else(backend):
    n = 7
    points = _grid_points(n)
    data = td.DataSet(points, td.StructuredCellSet((n, n, n)),
                      point_data={"r": _scalars(_sphere(points))})
    merged = td.contour(data, "r", 0.7)
    apart = td.contour(data, "r", 0.7, merge_points=False)
    mp, mt = _surface(merged)
    ap, at = _surface(apart)
    assert len(at) == len(mt) and len(ap) == 3 * len(at)
    assert _oriented(mp, mt) == _oriented(ap, at)
    assert len(np.unique(np.round(mp, 9), axis=0)) == len(mp)      # one point per edge


def test_cells_listing_shared_edges_in_opposite_directions(backend):
    """Every other hexahedron's points rotated a quarter turn about z: still a valid
    hexahedron, but its edges run the other way from its neighbours'. Points are
    interpolated from an edge's lower point id, so both cells make the same point."""
    n = 9
    points = _grid_points(n)
    rows = _hex_rows(n)
    rows[1::2] = rows[1::2][:, [3, 0, 1, 2, 7, 4, 5, 6]]
    data = td.DataSet(points, td.SingleTypeCellSet(sh.Hexahedron, rows),
                      point_data={"r": _scalars(_sphere(points))})
    pts, triangles = _surface(td.contour(data, "r", 0.55))
    assert (_edges(triangles) == 2).all()
    assert len(np.unique(pts, axis=0)) == len(pts)


def test_contours_that_miss_and_bad_values(backend):
    n = 5
    points = _grid_points(n)
    data = td.DataSet(points, td.StructuredCellSet((n, n, n)),
                      point_data={"r": _scalars(_sphere(points)),
                                  "id": tack.arange(len(points), tack.i32)})
    for isovalue in (5.0, -1.0):
        surface = td.contour(data, "r", isovalue)
        assert surface.num_cells == 0 and surface.num_points == 0
    with pytest.raises(TypeError, match="'values' is i32"):
        td.contour(data, "id", 1.0)
    flat = td.DataSet(np.zeros((4, 3)), td.SingleTypeCellSet(sh.Quad, [[0, 1, 2, 3]]),
                      point_data={"v": _scalars([0.0, 1.0, 1.0, 0.0])})
    assert td.contour(flat, "v", 0.5).num_cells == 0      # 2D cells contribute nothing


# ── VTK ─────────────────────────────────────────────────────────────

def _vtk_contour(data, name, isovalue):
    from tack.interop.vtk import dataset_to_vtk
    grid = dataset_to_vtk(data)
    grid.GetPointData().SetActiveScalars(name)
    contour = vtk.vtkContourGrid()
    contour.SetInputData(grid)
    contour.SetValue(0, isovalue)
    contour.Update()
    out = contour.GetOutput()
    if not out.GetNumberOfCells():
        return np.zeros((0, 3)), np.zeros((0, 3), int)
    polys = out.GetPolys()
    offsets = vtk_to_numpy(polys.GetOffsetsArray())
    connectivity = vtk_to_numpy(polys.GetConnectivityArray())
    triangles = np.array([connectivity[offsets[i]:offsets[i + 1]]
                          for i in range(len(offsets) - 1)])
    return vtk_to_numpy(out.GetPoints().GetData()), triangles


def _every_case(shape, rng):
    """One cell per case of ``shape``, apart from each other, with values above and below 0.5."""
    ref = np.array(EXPECTED[shape]["points"], float)
    n = len(ref)
    points, values, rows = [], [], []
    for case in range(2 ** n):
        corner = np.array([case % 16, (case // 16) % 16, case // 256], float) * 3.0
        rows.append(list(range(len(points), len(points) + n)))
        points.extend(corner + ref * 2.0)
        values.extend(0.5 + (1 if (case >> j) & 1 else -1) * rng.uniform(0.1, 0.4)
                      for j in range(n))
    return np.array(points), np.array(values), np.array(rows)


@needs_vtk
@pytest.mark.parametrize("shape", SOLIDS, ids=lambda cls: cls.__name__)
def test_every_case_of_every_shape_is_vtks(f64_backend, shape):
    points, values, rows = _every_case(shape, np.random.default_rng(int(shape.ID)))
    data = td.DataSet(points, td.SingleTypeCellSet(shape, rows), dtype=tack.f64,
                      point_data={"v": _scalars(values, tack.f64)})
    ours = _oriented(*_surface(td.contour(data, "v", 0.5)))
    theirs = _oriented(*_vtk_contour(data, "v", 0.5))
    assert len(ours) == len(theirs) and ours == theirs


@needs_vtk
@pytest.mark.parametrize("mesh", ["delaunay", "hexahedra and wedges", "mixed"])
def test_meshes_are_vtks(f64_backend, mesh):
    from tack.interop.vtk import vtk_to_dataset
    rng = np.random.default_rng(9)
    if mesh == "delaunay":
        cloud_points = vtk.vtkPoints()
        cloud_points.SetData(numpy_to_vtk(rng.uniform(-1, 1, (300, 3)), deep=1))
        cloud = vtk.vtkPolyData()
        cloud.SetPoints(cloud_points)
        delaunay = vtk.vtkDelaunay3D()
        delaunay.SetInputData(cloud)
        delaunay.Update()
        data = vtk_to_dataset(delaunay.GetOutput(), dtype=tack.f64)
    elif mesh == "hexahedra and wedges":
        from test_filters import _wedge_columns
        data = _wedge_columns(6)
    else:
        shapes_, rows, points = [], [], []
        for k, shape in enumerate(rng.choice(SOLIDS, 200)):
            ref = np.array(EXPECTED[shape]["points"], float)
            rows.append(list(range(len(points), len(points) + len(ref))))
            points.extend(rng.uniform(-1, 1, 3) + ref * rng.uniform(0.2, 0.5, 3))
            shapes_.append(shape.ID)
        offsets = np.concatenate([[0], np.cumsum([len(r) for r in rows])])
        data = td.DataSet(np.array(points), td.ExplicitCellSet(
            np.array(shapes_, np.uint8), offsets, np.concatenate(rows)), dtype=tack.f64)
    pts = data.points.to_numpy(vectors=True)
    data.point_data["r"] = _scalars(_sphere(pts), tack.f64)
    for isovalue in (0.4, 0.8):
        ours = _oriented(*_surface(td.contour(data, "r", isovalue)))
        theirs = _oriented(*_vtk_contour(data, "r", isovalue))
        assert len(ours) == len(theirs) and ours == theirs
