"""Tack AST transformation — Python AST to Tack IR.

Transforms a @kernel-decorated Python function's AST into Tack's internal IR.
Supports: parallel/sequential for-range loops, while loops, if/else, comparisons,
boolean ops, unary ops, math builtins, field indexing, type inference,
@tack.func inlining, multi-dimensional indexing, ndrange, and vector operations.

Inspired by Taichi's AST transformer (Apache 2.0), simplified for Tack's needs.
"""

import ast
import copy

from tack.lang import ir
from tack.lang.ir_names import fresh_name
from tack.lang.ir_traversal import walk_ir
from tack.lang.source_validation import UnsupportedSyntaxError, validate_source
from tack.lang.types import f32, f64, i8, i16, i32, i64, u8, u16, u32, u64

# Math builtins that map to LLVM intrinsics / libm calls
MATH_BUILTINS = {
    "sqrt", "sin", "cos", "tan",
    "asin", "acos", "atan", "atan2",
    "exp", "log", "log2", "log10",
    "floor", "ceil",
    "abs", "min", "max", "pow",
    "fabs",
    "exp2",
}

# Names for the first four components of a vector: v.x is v[0].
COMPONENT_NAMES = "xyzw"


class KernelTransformer(ast.NodeVisitor):
    """Transforms a Python AST (from a @kernel function) into Tack IR.

    Tracks nesting depth to distinguish parallel for-loops (top-level)
    from sequential for-loops (nested inside another for-loop).

    Supports:
      - @tack.func inlining at call sites
      - Multi-dimensional field indexing: field[i, j] → field[i * shape1 + j]
      - field[None] → field[0] for scalar fields
      - ndrange(w, h) → 1D parallel loop with index decomposition
      - Vector scalarization: Vector([a, b, c]) → 3 scalar variables
    """

    def __init__(self, vector_fields=None, texture_fields=None, python_func=None,
                 bindings=None, template_funcs=None):
        self._python_func = python_func
        self._bindings = bindings
        self._template_funcs = template_funcs
        self._call_bindings = None
        self._active_funcs = set()
        self._loop_depth = 0
        self._used_names: set[str] = set()
        self._component_names: dict[tuple[str, int], str] = {}
        self._inline_counter = 0  # unique suffix for inlined variables
        # Vector tracking: name → number of components
        self._vector_vars: dict[str, int] = {}
        # Statements generated by expression-level inlining (hoisted before current stmt)
        self._pre_stmts: list = []
        # Shared memory variables
        self._shared_vars: set[str] = set()
        # Vector field metadata: param_name → number of components
        self._vector_fields: dict[str, int] = vector_fields or {}
        # Texture field metadata: param_name → (W, H, D) shape
        self._texture_fields: dict[str, tuple] = texture_fields or {}
        # Maps renamed texture names back to the original kernel param name
        self._texture_origin: dict[str, str] = {}
        # Where each name is first read: name → (line, column, device
        # function it was inlined from or None). Only for diagnostics.
        self._name_reads: dict[str, tuple] = {}
        self._inline_stack: list[str] = []
        self._function_name = '<module>'
        # Statements outside the parallel loop may run any number of times
        # per launch (once per GPU thread, once per CPU chunk or probe), so
        # only effect-free ones are accepted there.
        self._kernel_body: list = []
        self._in_parallel_loop = False
        self._parallel_loop_seen = False

    def visit(self, node):
        try:
            return super().visit(node)
        except NotImplementedError as error:
            if isinstance(error, UnsupportedSyntaxError):
                raise
            line = getattr(node, 'lineno', 1)
            column = getattr(node, 'col_offset', 0) + 1
            raise UnsupportedSyntaxError(
                f"Kernel '{self._function_name}': {error} "
                f"at line {line}, column {column}") from error

    def visit_Module(self, node: ast.Module) -> ir.IRModule:
        module = ir.IRModule()
        for stmt in node.body:
            if isinstance(stmt, ast.FunctionDef):
                from tack.lang.call_bindings import CallBindings
                self._call_bindings = CallBindings(
                    stmt, self._python_func, self._bindings, self._template_funcs)
                validate_source(stmt, call_bindings=self._call_bindings)
                module.functions.append(self.visit_FunctionDef(stmt))
            else:
                raise NotImplementedError(f"Unsupported module statement: {type(stmt).__name__}")
        return module

    def generic_visit(self, node):
        raise NotImplementedError(f"Unsupported kernel syntax: {type(node).__name__}")

    def visit_Pass(self, node):
        return None

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ir.IRFunction:
        self._function_name = node.name
        self._used_names.update(n.id for n in ast.walk(node) if isinstance(n, ast.Name))
        self._used_names.update(arg.arg for arg in node.args.args)
        params = []
        for arg in node.args.args:
            params.append(ir.IRParam(
                name=arg.arg,
                type_annotation=None,  # resolved during type inference
            ))
        self._kernel_body = node.body
        body = self._visit_body(node.body)
        if not self._parallel_loop_seen:
            raise self._source_error(
                node, "definition", "has no parallel loop: a kernel's work is "
                "the body of one top-level `for` loop over `range(...)` or "
                "`tack.ndrange(...)`")
        for stmt in body:
            if isinstance(stmt, ir.IRParallelFor):
                _mark_outermost_continues(stmt.body)
        function = ir.IRFunction(name=node.name, params=params, body=body)
        self._check_names_bound(function)
        self._check_loop_variables_stay_in_their_loops(function)
        return function

    def _fresh_name(self, preferred):
        return fresh_name(preferred, self._used_names)

    def _source_error(self, node, construct, detail):
        """An UnsupportedSyntaxError at a kernel or inlined source position."""
        where = f"Kernel '{self._function_name}'"
        if self._inline_stack:
            where = (f"Device function '{self._inline_stack[-1]}' "
                     f"(inlined into kernel '{self._function_name}')")
        return UnsupportedSyntaxError(
            f"{where}: {construct} at line {node.lineno}, "
            f"column {node.col_offset + 1} {detail}")

    def _check_outside_parallel_loop(self, stmt, lowered: list):
        """Reject an observable effect lowered outside the parallel loop.

        Runs on each statement's lowered IR, so effects that arrive through
        inlined device functions, template methods, vector stores or tuple
        unpacking are all seen. Nested and inlined bodies are checked first,
        so the position is that of the innermost source statement.
        """
        for node in walk_ir([s for s in lowered if not isinstance(s, ir.IRParallelFor)]):
            effect = _effect_name(node)
            if effect is not None:
                raise self._source_error(
                    stmt, effect, "is outside the parallel loop. Statements "
                    "there may run any number of times per launch, so they "
                    "may only assign local variables and declare arrays; "
                    f"move the {effect} into the loop body")

    def _component_name(self, name, component):
        key = (name, component)
        if key not in self._component_names:
            self._component_names[key] = self._fresh_name(f"{name}__{component}")
        return self._component_names[key]

    def _check_names_bound(self, function: ir.IRFunction):
        """Reject a read of a name the kernel never binds.

        The usual cause is a module-level Python value: a kernel is compiled
        from its own source and captures nothing from the enclosing scope.
        The IR verifier would refuse the same thing a moment later, but only
        as a tree path into the lowered IR; here the source position is still
        known. Existence only -- not definite assignment on every path.
        """
        bound = {p.name for p in function.params}
        used = []
        for n in walk_ir(function.body):
            if isinstance(n, ir.IRAssign):
                bound.add(n.target)
            elif isinstance(n, (ir.IRParallelFor, ir.IRSequentialFor)):
                bound.add(n.var)
            elif isinstance(n, (ir.IRSharedAlloc, ir.IRLocalAlloc)):
                bound.add(n.name)
            elif isinstance(n, ir.IRName):
                used.append(n.name)
            elif isinstance(n, (ir.IRDimSize, ir.IRTextureSample)):
                used.append(n.field_name)
        for name in used:
            if name in bound:
                continue
            where = f"Kernel '{function.name}'"
            read = self._name_reads.get(name)
            at = ""
            if read is not None:
                line, column, inlined_from = read
                at = f" at line {line}, column {column}"
                if inlined_from is not None:
                    where = (f"Device function '{inlined_from}' "
                             f"(inlined into kernel '{function.name}')")
            raise NameError(
                f"{where}: name '{name}'{at} is not a parameter and is never "
                f"assigned. Kernels do not capture Python variables from the "
                f"enclosing scope: pass the value as an argument, or make it "
                f"a class-level constant of a @tack.data_oriented template.")

    def _check_loop_variables_stay_in_their_loops(self, function: ir.IRFunction):
        """Reject a read of a loop variable after its loop.

        A `for` loop's variable is a binding of its own that ends with the
        loop, on every backend: afterwards the name means whatever it meant
        before the loop, or nothing. Python would give the last value
        iterated. Rather than compute either silently -- CPU raised a
        NameError at codegen while the GPU backends failed to compile --
        refuse the read here, with its source position. A name whose most
        recent binding in program order is a loop header may not be read
        until it is assigned again. Branches and loops that may not run are
        merged conservatively: the name stays stale if it is stale on any
        path, so `assign it before the loop` is always a valid fix.
        """
        def read(expr, stale):
            for n in walk_ir(expr):
                if isinstance(n, ir.IRName) and n.name in stale:
                    raise self._loop_variable_error(function, n)

        def block(stmts, stale):
            stale = set(stale)
            for s in stmts:
                if isinstance(s, ir.IRAssign):
                    read(s.value, stale)
                    stale.discard(s.target)
                elif isinstance(s, (ir.IRSequentialFor, ir.IRParallelFor)):
                    for bound in (s.start, s.end, getattr(s, "step", None)):
                        if bound is not None:
                            read(bound, stale)
                    inner = block(s.body, stale - {s.var})
                    stale = (stale | inner) | {s.var}
                elif isinstance(s, ir.IRWhile):
                    read(s.condition, stale)
                    stale = stale | block(s.body, stale)
                elif isinstance(s, ir.IRIf):
                    read(s.condition, stale)
                    stale = block(s.then_body, stale) | block(s.else_body or [], stale)
                else:
                    read(s, stale)
            return stale

        block(function.body, set())

    def _loop_variable_error(self, function, name_node):
        where = f"Kernel '{function.name}'"
        at = ""
        read = getattr(name_node, "_source", None) or self._name_reads.get(name_node.name)
        if read is not None:
            line, column, inlined_from = read
            at = f" at line {line}, column {column}"
            if inlined_from is not None:
                where = (f"Device function '{inlined_from}' "
                         f"(inlined into kernel '{function.name}')")
        spelled = getattr(name_node, "_source_id", name_node.name)
        return NameError(
            f"{where}: name '{spelled}'{at} is read after the `for` loop "
            f"that bound it. A loop variable's binding ends with its loop; "
            f"to use the value afterwards, copy it to another name inside the "
            f"loop, or assign the name again before reading it.")

    def _visit_body(self, stmts: list) -> list:
        """Visit a list of statements, filtering out None results.

        Also collects any pre-statements generated by expression-level
        inlining of @tack.func calls and inserts them before the statement
        that triggered them.
        """
        saved_pre_stmts = self._pre_stmts
        result = []
        for stmt in stmts:
            self._pre_stmts = []
            visited = self.visit(stmt)
            # Insert any hoisted inline statements before this statement
            lowered = self._pre_stmts
            self._pre_stmts = []
            if visited is not None:
                if isinstance(visited, list):
                    lowered.extend(visited)
                else:
                    lowered.append(visited)
            if not self._in_parallel_loop:
                self._check_outside_parallel_loop(stmt, lowered)
            result.extend(lowered)
        self._pre_stmts = saved_pre_stmts
        return result

    def _visit_expression(self, node):
        """Capture the statements needed to evaluate exactly this expression."""
        saved = self._pre_stmts
        self._pre_stmts = []
        value = self.visit(node)
        statements = self._pre_stmts
        self._pre_stmts = saved
        return value, statements

    def _capture_value(self, value, statements, *, freeze_name=False):
        """Evaluate a delayed value before a later operand's side effects."""
        if isinstance(value, list):
            return [self._capture_value(v, statements) for v in value]
        if isinstance(value, ir.IRConstant) or (isinstance(value, ir.IRName) and not freeze_name):
            return value
        name = self._fresh_name(f"__eval_{self._inline_counter}__")
        self._inline_counter += 1
        statements.append(ir.IRAssign(name, value))
        return ir.IRName(name)

    def _visit_ordered(self, nodes):
        """Preserve left-to-right evaluation across expression-level inlining."""
        values = []
        for node in nodes:
            value, statements = self._visit_expression(node)
            if statements:
                values = [self._capture_value(v, self._pre_stmts) for v in values]
                self._pre_stmts.extend(statements)
            values.append(value)
        return values

    # --- Loops ---

    def visit_For(self, node: ast.For) -> ir.IRNode:
        if not self._in_parallel_loop:
            return self._visit_parallel_for(node)
        return self._visit_for(node)

    def _visit_parallel_for(self, node: ast.For) -> ir.IRParallelFor:
        """Lower the kernel's one parallel loop, a statement of its own body."""
        if self._parallel_loop_seen or not any(node is s for s in self._kernel_body):
            raise self._source_error(
                node, "for loop", "is outside the parallel loop. A kernel has "
                "one parallel loop, a `for` statement directly in its body; "
                "sequential loops belong inside it")
        self._parallel_loop_seen = True
        return self._visit_for(node)

    def _visit_for_body(self, stmts: list) -> list:
        """Lower a for-loop body, which always lies inside the parallel loop.

        Its range arguments were lowered before, where the loop is entered.
        """
        saved = self._in_parallel_loop
        self._in_parallel_loop = True
        self._loop_depth += 1
        body = self._visit_body(stmts)
        self._loop_depth -= 1
        self._in_parallel_loop = saved
        return body

    def _visit_for(self, node: ast.For) -> ir.IRNode:
        target = node.target

        if node.orelse:
            raise NotImplementedError("'else' clause on for-loop not supported in kernels")

        # Handle tuple targets: for i, j in ndrange(w, h)
        if isinstance(target, ast.Tuple):
            return self._visit_ndrange_for(node)

        if not isinstance(target, ast.Name):
            raise NotImplementedError("Only simple loop variables supported")

        # Detect for i in range(...)
        if not self._is_range_call(node.iter):
            raise NotImplementedError("Only range() loops supported in kernels")

        start, end, step = self._parse_range_args(node.iter)
        if self._loop_depth:
            # Python's range evaluates its arguments once, before entering
            # the loop, even when the body rebinds a bound or step variable.
            start = self._capture_value(start, self._pre_stmts, freeze_name=True)
            end = self._capture_value(end, self._pre_stmts, freeze_name=True)
            if step is not None:
                step = self._capture_value(step, self._pre_stmts, freeze_name=True)

        body = self._visit_for_body(node.body)

        # Top-level for-range is parallel; nested for-range is sequential
        if self._loop_depth == 0:
            if step is not None:
                # Transform: for i in range(start, end, step)
                # Into: for __step_idx__ in range(0, (end - start + step - 1) // step):
                #            i = start + __step_idx__ * step
                idx_name = self._fresh_name(f"__step_idx_{self._inline_counter}__")
                self._inline_counter += 1
                total = ir.IRBinOp(
                    op="//",
                    left=ir.IRBinOp(op="+",
                        left=ir.IRBinOp(op="-", left=end, right=start),
                        right=ir.IRBinOp(op="-", left=step, right=ir.IRConstant(1))),
                    right=step,
                )
                decomp = ir.IRAssign(
                    target=target.id,
                    value=ir.IRBinOp(op="+", left=start,
                        right=ir.IRBinOp(op="*", left=ir.IRName(idx_name), right=step)),
                )
                return ir.IRParallelFor(var=idx_name, start=ir.IRConstant(0),
                                        end=total, body=[decomp, *body])
            if not (isinstance(start, ir.IRConstant) and start.value == 0):
                # Every backend launches the grid over [0, n) and never sees
                # the start, so it has to live in the body.
                # Transform: for i in range(start, end)
                # Into: for __start_idx__ in range(0, end - start):
                #            i = start + __start_idx__
                idx_name = self._fresh_name(f"__start_idx_{self._inline_counter}__")
                self._inline_counter += 1
                decomp = ir.IRAssign(
                    target=target.id,
                    value=ir.IRBinOp(op="+", left=start, right=ir.IRName(idx_name)),
                )
                return ir.IRParallelFor(
                    var=idx_name, start=ir.IRConstant(0),
                    end=ir.IRBinOp(op="-", left=end, right=start),
                    body=[decomp, *body])
            return ir.IRParallelFor(var=target.id, start=start, end=end, body=body)
        return ir.IRSequentialFor(var=target.id, start=start, end=end,
                                  body=body, step=step)

    def _visit_ndrange_for(self, node: ast.For):
        """Handle: for i, j in ndrange(w, h) or for i, j in tack.ndrange(w, h)."""
        target = node.target
        if not isinstance(target, ast.Tuple):
            raise NotImplementedError("ndrange requires tuple target")

        names = []
        for elt in target.elts:
            if not isinstance(elt, ast.Name):
                raise NotImplementedError("ndrange targets must be simple names")
            names.append(elt.id)

        # Parse ndrange call
        call = node.iter
        if not isinstance(call, ast.Call):
            raise NotImplementedError("Expected ndrange() call")

        func_name = self._resolve_call_name(call)
        if func_name != "ndrange":
            raise NotImplementedError(f"Expected ndrange(), got {func_name}()")

        if len(call.args) != len(names):
            raise NotImplementedError(
                f"ndrange() dimension count ({len(call.args)}) must match "
                f"target count ({len(names)})"
            )

        dim_exprs = [self.visit(a) for a in call.args]

        # Compute total = dim0 * dim1 * ...
        total = dim_exprs[0]
        for d in dim_exprs[1:]:
            total = ir.IRBinOp(op="*", left=total, right=d)

        # Build body: decompose linear index into multi-dim indices
        # for __nd_idx__ in range(total):
        #     i = __nd_idx__ // dim1
        #     j = __nd_idx__ % dim1
        # For 3D: i = idx // (d1*d2), j = (idx // d2) % d1, k = idx % d2
        idx_name = self._fresh_name(f"__nd_idx_{self._inline_counter}__")
        self._inline_counter += 1

        decomp_stmts = []
        remaining = ir.IRName(idx_name)

        for k in range(len(names) - 1):
            # Product of remaining dimensions
            tail_product = dim_exprs[k + 1]
            for d in dim_exprs[k + 2:]:
                tail_product = ir.IRBinOp(op="*", left=tail_product, right=d)

            decomp_stmts.append(
                ir.IRAssign(target=names[k],
                            value=ir.IRBinOp(op="//", left=remaining, right=tail_product))
            )
            remaining = ir.IRBinOp(op="%", left=remaining, right=tail_product)

        # Last dimension gets the remainder
        decomp_stmts.append(ir.IRAssign(target=names[-1], value=remaining))

        body_stmts = self._visit_for_body(node.body)

        full_body = decomp_stmts + body_stmts

        if self._loop_depth == 0:
            return ir.IRParallelFor(
                var=idx_name, start=ir.IRConstant(0), end=total, body=full_body)
        return ir.IRSequentialFor(
            var=idx_name, start=ir.IRConstant(0), end=total, body=full_body)

    def visit_While(self, node: ast.While) -> ir.IRWhile:
        if node.orelse:
            raise NotImplementedError("'else' clause on while-loop not supported in kernels")
        condition, condition_stmts = self._visit_expression(node.test)
        self._loop_depth += 1
        body = self._visit_body(node.body)
        self._loop_depth -= 1
        if condition_stmts:
            # The condition's inlined calls execute on every test, including
            # after continue, rather than once before entering the loop.
            body = [*condition_stmts,
                    ir.IRIf(ir.IRUnaryOp('not', condition), [ir.IRBreak()], []),
                    *body]
            condition = ir.IRConstant(1)
        return ir.IRWhile(condition=condition, body=body)

    def visit_Break(self, node: ast.Break) -> ir.IRBreak:
        return ir.IRBreak()

    def visit_Continue(self, node: ast.Continue) -> ir.IRContinue:
        return ir.IRContinue()

    # --- Control flow ---

    def visit_If(self, node: ast.If) -> ir.IRIf:
        condition = self.visit(node.test)
        then_body = self._visit_body(node.body)
        else_body = self._visit_body(node.orelse)
        return ir.IRIf(condition=condition, then_body=then_body, else_body=else_body)

    def visit_IfExp(self, node: ast.IfExp) -> ir.IRIfExp:
        condition, before = self._visit_expression(node.test)
        then_value, then_stmts = self._visit_expression(node.body)
        else_value, else_stmts = self._visit_expression(node.orelse)
        self._pre_stmts.extend(before)
        if isinstance(then_value, list) or isinstance(else_value, list):
            return self._vector_conditional(
                node, condition, then_value, then_stmts, else_value, else_stmts)
        if then_stmts or else_stmts:
            name = self._fresh_name(f"__conditional_{self._inline_counter}__")
            self._inline_counter += 1
            self._pre_stmts.append(ir.IRIf(
                condition,
                [*then_stmts, ir.IRAssign(name, then_value)],
                [*else_stmts, ir.IRAssign(name, else_value)],
            ))
            return ir.IRName(name)
        return ir.IRIfExp(condition, then_value, else_value)

    def _vector_conditional(self, node, condition, then_value, then_stmts,
                            else_value, else_stmts):
        """``a if c else b`` with a vector arm: one selection per component.

        The condition is evaluated once. An arm that needs statements of
        its own (an inlined call) runs them only when it is selected.
        """
        then_value, else_value = zip(*self._componentwise(
            node, "conditional expression", [then_value, else_value]), strict=True)
        if then_stmts or else_stmts:
            names = []
            for _ in then_value:
                names.append(self._fresh_name(f"__conditional_{self._inline_counter}__"))
                self._inline_counter += 1
            self._pre_stmts.append(ir.IRIf(
                condition,
                [*then_stmts, *(ir.IRAssign(n, v) for n, v in zip(names, then_value))],
                [*else_stmts, *(ir.IRAssign(n, v) for n, v in zip(names, else_value))],
            ))
            return [ir.IRName(n) for n in names]
        condition = self._capture_value(condition, self._pre_stmts)
        return [ir.IRIfExp(condition, t, e) for t, e in zip(then_value, else_value)]

    # --- Assignments ---

    def visit_Assign(self, node: ast.Assign) -> ir.IRNode:
        if len(node.targets) != 1:
            raise NotImplementedError("Multiple assignment targets not supported")

        target = self._component_target(node.targets[0])
        value = node.value

        # Tuple unpacking: a, b = expr
        if isinstance(target, ast.Tuple):
            return self._visit_tuple_unpack(target, value)

        # Check for shared memory allocation: smem = tack.shared(tack.f32, 256)
        #                             or: smem = tack.shared_like(field, 256)
        if isinstance(target, ast.Name) and isinstance(value, ast.Call):
            shared_result = self._try_parse_shared_alloc(target.id, value)
            if shared_result is not None:
                return shared_result
            shared_like_result = self._try_parse_shared_like(target.id, value)
            if shared_like_result is not None:
                return shared_like_result

        # Check for local array allocation: arr = tack.local_array(tack.f32, 8)
        #                            or: arr = tack.local_array_like(field, 8)
        if isinstance(target, ast.Name) and isinstance(value, ast.Call):
            local_result = self._try_parse_local_alloc(target.id, value)
            if local_result is not None:
                return local_result
            local_like_result = self._try_parse_local_array_like(target.id, value)
            if local_like_result is not None:
                return local_like_result

        if (isinstance(target, ast.Name) and isinstance(value, ast.Name)
                and value.id in self._shared_vars):
            # An array is storage, not a value: C has no array assignment,
            # and binding a second name to it lowers to a scalar copy.
            raise NotImplementedError(
                f"cannot bind '{target.id}' to the local or shared array "
                f"'{value.id}'; index '{value.id}' directly, or pass it to "
                f"a @tack.func")

        # Check for vector construction: v = tack.Vector([a, b, c])
        vec_elts = self._try_parse_vector_construct(value)
        if vec_elts is not None and isinstance(target, ast.Name):
            return self._assign_vector(target.id, vec_elts)

        visited_value = self.visit(value)

        # v[c] = expr for a vector variable: assign the component
        if (isinstance(target, ast.Subscript) and isinstance(target.value, ast.Name)
                and target.value.id in self._vector_vars):
            return self._store_vector_component(target, visited_value)

        # vf[i][c] = expr for a vector field: store the component
        if self._is_field_component(target):
            return self._assign_field_component(target, visited_value)

        # Check if RHS is a vector variable → propagate vector-ness
        if isinstance(visited_value, list):
            # Vector expression result (list of IR nodes)
            if isinstance(target, ast.Name):
                return self._assign_vector_from_ir(target.id, visited_value)
            # Vector store: field[i] = vec_var
            if isinstance(target, ast.Subscript):
                return self._store_vector_field(target, visited_value)

        # field[i] = expr  →  IRFieldStore
        if isinstance(target, ast.Subscript):
            field, index, visited_value = self._visit_store_location(target, visited_value)
            return ir.IRFieldStore(field=field, index=index, value=visited_value)

        # x = expr  →  IRAssign
        if isinstance(target, ast.Name):
            # Clear vector tracking if reassigning to scalar
            self._vector_vars.pop(target.id, None)
            return ir.IRAssign(target=target.id, value=visited_value)

        raise NotImplementedError(f"Unsupported assignment target: {type(target).__name__}")

    def visit_AugAssign(self, node: ast.AugAssign) -> ir.IRNode:
        target = self._component_target(node.target)
        op = self._binop_str(node.op)

        # Check for vector augmented assignment: v += w
        if isinstance(target, ast.Name) and target.id in self._vector_vars:
            ndim = self._vector_vars[target.id]
            rhs_components = self._visit_as_vector(node.value, ndim)
            names = [self._component_name(target.id, c) for c in range(ndim)]
            stmts = []
            updated = self._settle_components(
                [ir.IRBinOp(op=op, left=ir.IRName(name), right=rhs)
                 for name, rhs in zip(names, rhs_components)], stmts, names)
            for name, value in zip(names, updated):
                stmts.append(ir.IRAssign(target=name, value=value))
            return stmts

        # v[c] += expr for a vector variable: read the component, store it back
        if (isinstance(target, ast.Subscript) and isinstance(target.value, ast.Name)
                and target.value.id in self._vector_vars):
            read = self.visit(target)
            right, statements = self._visit_expression(node.value)
            self._pre_stmts.extend(statements)
            return self._store_vector_component(
                target, ir.IRBinOp(op=op, left=read, right=right))

        # vf[i][c] += expr, and vf[i] += vec, for a vector field
        if self._is_field_component(target):
            return self._augment_field_component(target, op, node.value)
        if (isinstance(target, ast.Subscript) and isinstance(target.value, ast.Name)
                and target.value.id in self._vector_fields):
            return self._augment_vector_field(target, op, node.value)

        left = self.visit(target)
        # Evaluate a subscript once, reusing its address for the store.
        if isinstance(left, ir.IRFieldLoad):
            left.index = self._capture_value(left.index, self._pre_stmts)
        right, statements = self._visit_expression(node.value)
        if statements:
            read = self._capture_value(left, self._pre_stmts)
            self._pre_stmts.extend(statements)
        else:
            read = left
        if isinstance(right, list):
            raise self._source_error(
                node, "augmented assignment", "combines a scalar target with a vector")
        rhs = ir.IRBinOp(op=op, left=read, right=right)

        if isinstance(target, ast.Subscript):
            return ir.IRFieldStore(field=left.field, index=left.index, value=rhs)

        if isinstance(target, ast.Name):
            return ir.IRAssign(target=target.id, value=rhs)

        raise NotImplementedError("Unsupported augmented assignment target")

    def visit_Return(self, node: ast.Return) -> ir.IRReturn:
        value = self.visit(node.value) if node.value else None
        return ir.IRReturn(value=value)

    def _visit_tuple_unpack(self, target: ast.Tuple, value_node: ast.expr) -> list:
        """Handle tuple unpacking: a, b = expr."""
        names = []
        for elt in target.elts:
            if not isinstance(elt, ast.Name):
                raise NotImplementedError("Only simple names in tuple unpacking")
            names.append(elt.id)
        n = len(names)

        # Tuple literal RHS: a, b = b, a (need temps for correct swap)
        if isinstance(value_node, ast.Tuple):
            if len(value_node.elts) != n:
                raise TypeError(
                    f"Tuple unpacking: expected {n} values, got {len(value_node.elts)}")
            stmts = []
            temps = []
            for i, val in enumerate(self._visit_ordered(value_node.elts)):
                tmp = self._fresh_name(f"__unpack_tmp_{self._inline_counter}_{i}__")
                if isinstance(val, list):
                    ndim = len(val)
                    self._vector_vars[tmp] = ndim
                    for c, comp in enumerate(val):
                        stmts.append(ir.IRAssign(target=self._component_name(tmp, c), value=comp))
                    temps.append(('vector', tmp, ndim))
                else:
                    stmts.append(ir.IRAssign(target=tmp, value=val))
                    temps.append(('scalar', tmp, None))
            self._inline_counter += 1
            # Assign temps to targets
            for name, (kind, tmp, ndim) in zip(names, temps):
                if kind == 'vector':
                    self._vector_vars[name] = ndim
                    for c in range(ndim):
                        stmts.append(ir.IRAssign(
                            target=self._component_name(name, c),
                            value=ir.IRName(self._component_name(tmp, c))))
                else:
                    self._vector_vars.pop(name, None)
                    stmts.append(ir.IRAssign(target=name, value=ir.IRName(tmp)))
            return stmts

        # Expression RHS (e.g., multi-return from @tack.func)
        visited_value = self.visit(value_node)

        if isinstance(visited_value, list):
            if len(visited_value) != n:
                raise TypeError(
                    f"Tuple unpacking: expected {n} values, got {len(visited_value)}")
            stmts = []
            visited_value = self._settle_components(visited_value, stmts, names)
            for name, val in zip(names, visited_value):
                self._vector_vars.pop(name, None)
                stmts.append(ir.IRAssign(target=name, value=val))
            return stmts

        raise NotImplementedError("Cannot unpack non-tuple value")

    # --- Expressions ---

    def visit_BinOp(self, node: ast.BinOp) -> ir.IRNode:
        op = self._binop_str(node.op)
        left, right = self._visit_ordered([node.left, node.right])

        # Vector-scalar or vector-vector binary ops
        left_is_vec = isinstance(left, list)
        right_is_vec = isinstance(right, list)

        if left_is_vec or right_is_vec:
            if left_is_vec and right_is_vec:
                if len(left) != len(right):
                    raise TypeError("Vector dimension mismatch in binary op")
                return [ir.IRBinOp(op=op, left=l, right=r) for l, r in zip(left, right)]
            if left_is_vec:
                return [ir.IRBinOp(op=op, left=l, right=right) for l in left]
            return [ir.IRBinOp(op=op, left=left, right=r) for r in right]

        return ir.IRBinOp(op=op, left=left, right=right)

    def visit_UnaryOp(self, node: ast.UnaryOp) -> ir.IRNode:
        op = self._unaryop_str(node.op)
        operand = self.visit(node.operand)

        # A signed integer literal is classified by its complete value.
        # In particular, -2**63 fits i64 even though its positive token does not.
        if op in ('+', '-') and isinstance(operand, ir.IRConstant) and isinstance(operand.value, int):
            return ir.IRConstant(-operand.value if op == '-' else operand.value)

        if isinstance(operand, list):
            return [ir.IRUnaryOp(op=op, operand=c) for c in operand]

        return ir.IRUnaryOp(op=op, operand=operand)

    def visit_Compare(self, node: ast.Compare) -> ir.IRNode:
        if len(node.ops) == 1:
            left, right = self._visit_ordered([node.left, node.comparators[0]])
            return ir.IRCompare(self._cmpop_str(node.ops[0]), left, right)

        operands = [self._visit_expression(n) for n in [node.left, *node.comparators]]
        if any(stmts for _, stmts in operands):
            name = self._fresh_name(f"__comparison_{self._inline_counter}__")
            self._inline_counter += 1
            left, before = operands[0]
            self._pre_stmts.extend(before)
            left = self._capture_value(left, self._pre_stmts)

            def lower_link(index, previous):
                right, before = operands[index + 1]
                body = list(before)
                right = self._capture_value(right, body)
                comparison = ir.IRCompare(self._cmpop_str(node.ops[index]), previous, right)
                body.append(ir.IRAssign(name, comparison))
                if index + 1 < len(node.ops):
                    body.append(ir.IRIf(ir.IRName(name), lower_link(index + 1, right), []))
                return body

            self._pre_stmts.extend(lower_link(0, left))
            return ir.IRName(name)

        # Desugar chained comparisons: a < b < c  →  (a < b) and (b < c)
        comparisons = []
        left = operands[0][0]
        for op_node, (right, _) in zip(node.ops, operands[1:]):
            op = self._cmpop_str(op_node)
            comparisons.append(ir.IRCompare(op=op, left=left, right=right))
            left = right

        if len(comparisons) == 1:
            return comparisons[0]
        return ir.IRBoolOp(op="and", values=comparisons)

    def visit_BoolOp(self, node: ast.BoolOp) -> ir.IRBoolOp:
        op = "and" if isinstance(node.op, ast.And) else "or"
        operands = [self._visit_expression(n) for n in node.values]
        values = [value for value, _ in operands]
        if any(stmts for _, stmts in operands):
            name = self._fresh_name(f"__boolean_{self._inline_counter}__")
            self._inline_counter += 1
            value, before = operands[0]
            self._pre_stmts.extend(before)
            self._pre_stmts.append(ir.IRAssign(name, ir.IRCompare('!=', value, ir.IRConstant(0))))
            for value, before in operands[1:]:
                guard = ir.IRName(name)
                if op == 'or':
                    guard = ir.IRUnaryOp('not', guard)
                self._pre_stmts.append(ir.IRIf(
                    guard,
                    [*before, ir.IRAssign(name, ir.IRCompare('!=', value, ir.IRConstant(0)))],
                    [],
                ))
            return ir.IRName(name)
        return ir.IRBoolOp(op=op, values=values)

    def visit_Subscript(self, node: ast.Subscript) -> ir.IRNode:
        # Vector component access: v[0], or v[k] for a runtime k
        if isinstance(node.value, ast.Name) and node.value.id in self._vector_vars:
            ndim = self._vector_vars[node.value.id]
            components = [ir.IRName(self._component_name(node.value.id, c)) for c in range(ndim)]
            return self._vector_component(node, components)

        # A component of a vector-valued expression: vf[i][c], f(x)[c]
        if isinstance(node.value, (ast.Subscript, ast.Call)):
            inner, statements = self._visit_expression(node.value)
            self._pre_stmts.extend(statements)
            if isinstance(inner, list):
                return self._vector_component(node, inner)
            raise self._source_error(
                node, "subscript", "indexes a scalar value; only fields, local and "
                "shared arrays, and vectors can be indexed")

        # field.shape[k] — a dimension query, not a load from a field
        dim_size = self._as_dim_size(node)
        if dim_size is not None:
            return dim_size

        # Get field name for vector field detection
        field_name = node.value.id if isinstance(node.value, ast.Name) else None
        is_vector_field = field_name is not None and field_name in self._vector_fields

        # Compute the linearized index (handles multi-dim, None, etc.)
        index = self._visit_subscript_index(node)
        field_ir = self.visit(node.value)

        # Vector field load: expand to n component loads
        if is_vector_field:
            ndim = self._vector_fields[field_name]
            # Cast index to int before computing component offsets so that
            # a float index like 127.7 maps to element 127, not a fractional
            # position that shifts the component access.
            int_index = ir.IRCast(value=index, dtype=i32)
            return [ir.IRFieldLoad(field=field_ir, index=self._component_index(int_index, ndim, c))
                    for c in range(ndim)]

        return ir.IRFieldLoad(field=field_ir, index=index)

    def _as_dim_size(self, node: ast.Subscript) -> ir.IRDimSize | None:
        """`f.shape[k]` on a field → IRDimSize, which resolve_ir folds.

        Emitting a generic IRAttribute here is what limited `.shape` to the
        outermost loop bound: dispatch evaluated that one expression
        numerically, and every other position reached codegen unresolved.
        IRDimSize is the node the resolve pass already knows how to fold,
        and it recurses through every body.
        """
        value = node.value
        if not (isinstance(value, ast.Attribute) and value.attr == "shape"):
            return None
        if not isinstance(value.value, ast.Name):
            return None
        index = node.slice
        if not (isinstance(index, ast.Constant) and isinstance(index.value, int)):
            raise NotImplementedError(
                f"'{value.value.id}.shape[...]' needs a constant dimension "
                f"index; the shape is resolved when the kernel is compiled."
            )
        return ir.IRDimSize(field_name=value.value.id, dim=index.value)

    def visit_Attribute(self, node: ast.Attribute) -> ir.IRAttribute:
        obj = self.visit(node.value)
        if isinstance(obj, list):
            # v.x on a vector variable or a vector-valued expression
            return obj[self._named_component(node, len(obj))]
        return ir.IRAttribute(obj=obj, attr=node.attr)

    def _named_component(self, node: ast.Attribute, n: int) -> int:
        """The index that ``x``, ``y``, ``z`` or ``w`` names in an n-vector."""
        c = COMPONENT_NAMES.find(node.attr) if len(node.attr) == 1 else -1
        if not 0 <= c < n:
            names = ", ".join(COMPONENT_NAMES[:n])
            raise self._source_error(
                node, "attribute", f"'{node.attr}' is not a component of a {n}-vector; "
                f"use {names} or an index")
        return c

    def _component_target(self, target):
        """An assignment target ``v.x`` or ``vf[i].x`` as the subscript it names."""
        if not isinstance(target, ast.Attribute):
            return target
        vector = target.value
        if isinstance(vector, ast.Name) and vector.id in self._vector_vars:
            n = self._vector_vars[vector.id]
        elif (isinstance(vector, ast.Subscript) and isinstance(vector.value, ast.Name)
                and vector.value.id in self._vector_fields):
            n = self._vector_fields[vector.value.id]
        else:
            return target
        index = ast.copy_location(ast.Constant(self._named_component(target, n)), target)
        return ast.copy_location(ast.Subscript(value=vector, slice=index, ctx=target.ctx), target)

    def visit_Name(self, node: ast.Name) -> ir.IRNode:
        source = None
        if hasattr(node, 'lineno'):
            source = (node.lineno, node.col_offset + 1,
                      self._inline_stack[-1] if self._inline_stack else None)
            self._name_reads.setdefault(node.id, source)
        # If this name is a vector variable, return its components as a list
        if node.id in self._vector_vars:
            ndim = self._vector_vars[node.id]
            return [ir.IRName(self._component_name(node.id, c)) for c in range(ndim)]
        name = ir.IRName(name=node.id)
        # This read's position and source spelling, for scope errors.
        name._source = source
        name._source_id = getattr(node, '_source_id', node.id)
        return name

    def visit_Constant(self, node: ast.Constant) -> ir.IRConstant:
        return ir.IRConstant(value=node.value)

    def visit_Tuple(self, node: ast.Tuple) -> list:
        """Visit tuple — used for multi-dimensional indexing like field[i, j]."""
        return self._visit_ordered(node.elts)

    def visit_Call(self, node: ast.Call) -> ir.IRNode:
        # Check for @tack.func calls → inline
        func_obj = self._call_bindings.device_func(node.func)
        if func_obj is not None:
            return self._inline_func_call(func_obj, node)
        func_name = self._resolve_call_name(node)

        # Vector constructor: Vector([a, b, c]) or tack.Vector([a, b, c])
        if func_name == "Vector":
            return self._visit_vector_construct(node)

        # Math builtins from the math module or bare names
        if func_name in MATH_BUILTINS:
            arity = 2 if func_name in ('atan2', 'pow', 'min', 'max') else 1
            if len(node.args) != arity:
                raise NotImplementedError(f"{func_name}() takes exactly {arity} arguments")
            args = self._visit_ordered(node.args)
            if any(isinstance(a, list) for a in args):
                return [ir.IRCall(func_name=func_name, args=row)
                        for row in self._componentwise(node, f"{func_name}()", args)]
            return ir.IRCall(func_name=func_name, args=args)

        # len(field) → the field's first dimension
        if func_name == "len":
            if len(node.args) != 1:
                raise NotImplementedError("len() takes exactly one argument")
            target = node.args[0]
            if isinstance(target, ast.Name) and target.id not in self._vector_vars:
                return ir.IRDimSize(field_name=target.id, dim=0)
            arg = self.visit(target)
            return ir.IRAttribute(obj=arg, attr="__len__")

        # range() is handled in visit_For; if it appears elsewhere, error
        if func_name == "range":
            raise NotImplementedError("range() outside of for-loop not supported")

        # ndrange() outside of for-loop
        if func_name == "ndrange":
            raise NotImplementedError("ndrange() outside of for-loop not supported")

        # Shared memory: tack.shared(dtype, size) or tack.shared_like(field, size)
        if func_name == "shared":
            raise NotImplementedError(
                "tack.shared() must be used in an assignment: smem = tack.shared(tack.f32, 256)")
        if func_name == "shared_like":
            raise NotImplementedError(
                "tack.shared_like() must be used in an assignment: smem = tack.shared_like(field, 256)")

        # Local array: tack.local_array(dtype, size) or tack.local_array_like(field, size)
        if func_name == "local_array":
            raise NotImplementedError(
                "tack.local_array() must be used in an assignment: arr = tack.local_array(tack.f32, 8)")
        if func_name == "local_array_like":
            raise NotImplementedError(
                "tack.local_array_like() must be used in an assignment: arr = tack.local_array_like(field, 8)")

        # Block reductions: tack.block_sum(val), tack.block_max(val), tack.block_min(val)
        if func_name in ("block_sum", "block_max", "block_min"):
            if len(node.args) != 1:
                raise NotImplementedError(f"tack.{func_name}() takes exactly 1 argument")
            op = func_name.replace("block_", "")  # "sum", "max", "min"
            return ir.IRBlockReduce(op=op, value=self.visit(node.args[0]))

        # Barrier: tack.barrier()
        if func_name == "barrier":
            return ir.IRBarrier()

        # Thread ID: tack.thread_id()
        if func_name == "thread_id":
            return ir.IRThreadId()

        # Atomic operations: atomic_add, atomic_min, atomic_max
        if func_name in ("atomic_add", "atomic_min", "atomic_max"):
            if len(node.args) != 3:
                raise NotImplementedError(f"{func_name}() takes exactly 3 arguments (field, index, value)")
            field, index, value = self._visit_ordered(node.args)
            op = func_name.replace("atomic_", "")  # "add", "min", "max"
            return ir.IRAtomicOp(op=op, field=field, index=index, value=value)

        # print() for kernel debugging
        if func_name == "print":
            format_parts = []
            expr_nodes = []
            for arg in node.args:
                if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                    format_parts.append(("str", arg.value))
                else:
                    format_parts.append(("expr", len(expr_nodes)))
                    expr_nodes.append(arg)
            return ir.IRPrint(args=self._visit_ordered(expr_nodes), format_parts=format_parts)

        # Type casts: int(), float(), and explicit tack.f32/f64/i32/i64/u32/u64
        _CAST_MAP = {
            "int": i32, "float": f32,
            "i8": i8, "u8": u8,
            "i16": i16, "u16": u16,
            "i32": i32, "u32": u32,
            "i64": i64, "u64": u64,
            "f32": f32, "f64": f64,
        }
        if func_name in _CAST_MAP:
            if len(node.args) != 1:
                raise NotImplementedError(f"{func_name}() takes exactly one argument")
            value = self.visit(node.args[0])
            if isinstance(value, list):
                return [ir.IRCast(value=c, dtype=_CAST_MAP[func_name]) for c in value]
            return ir.IRCast(value=value, dtype=_CAST_MAP[func_name])

        # Check for texture3d.sample(u, v, w)
        if isinstance(node.func, ast.Attribute) and node.func.attr == "sample":
            tex_name = getattr(node.func.value, 'id', None)
            if tex_name and tex_name in self._texture_fields:
                if len(node.args) != 3:
                    raise TypeError("sample() takes exactly 3 arguments (u, v, w)")
                coords = [self.visit(a) for a in node.args]
                # Use the original kernel param name, not the inlined rename
                original_name = self._texture_origin.get(tex_name, tex_name)
                return ir.IRTextureSample(
                    field_name=original_name, coords=coords)

        # Check for vector method calls: v.normalized(), v.cross(w), v.dot(w), v.norm()
        if isinstance(node.func, ast.Attribute):
            obj_result = self._try_visit_vector_method(node)
            if obj_result is not None:
                return obj_result

        raise NotImplementedError(f"Function call '{func_name}' not supported in kernels")

    def visit_Expr(self, node: ast.Expr) -> ir.IRNode:
        """Expression statement (e.g., standalone function call)."""
        # Skip docstrings and other standalone string constants
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            return None
        value = self.visit(node.value)
        # A function/atomic expression can have generated all its effects
        # in pre-statements. Its scalar result is unused here.
        return None if isinstance(value, (ir.IRName, list)) else value

    # --- @tack.func inlining ---

    def _inline_func_call(self, func_obj, call_node: ast.Call):
        """Inline a @tack.func call, tracking it for diagnostics."""
        # Arguments belong to the caller's source; visiting them first
        # records their positions before the callee's are in play.
        for arg in call_node.args:
            for sub in ast.walk(arg):
                if (isinstance(sub, ast.Name) and hasattr(sub, 'lineno')
                        and sub.id not in self._name_reads):
                    self._name_reads[sub.id] = (
                        sub.lineno, sub.col_offset + 1,
                        self._inline_stack[-1] if self._inline_stack else None)
        # Template methods are renamed; diagnostics use the source name.
        self._inline_stack.append(func_obj.func.__name__)
        try:
            return self._inline_func_body(func_obj, call_node)
        finally:
            self._inline_stack.pop()

    def _inline_func_body(self, func_obj, call_node: ast.Call):
        """Inline a @tack.func call at the call site.

        Produces a list of IR statements (parameter assignments + body),
        and returns the result variable name as an IRName.
        """
        from tack.lang.call_bindings import CallBindings
        func_name = func_obj.name
        funcdef = func_obj._funcdef
        callee_bindings = CallBindings(funcdef, func_obj.func,
                                      template_funcs=self._template_funcs)
        validate_source(funcdef, kind='Device function', call_bindings=callee_bindings)

        # Save and reset _pre_stmts so nested inlining doesn't interfere
        saved_pre_stmts = self._pre_stmts
        self._pre_stmts = []

        # Unique suffix to avoid name collisions across multiple inlines
        suffix = self._inline_counter
        self._inline_counter += 1

        # Map callee params to caller args
        callee_params = [a.arg for a in funcdef.args.args]
        if len(call_node.args) != len(callee_params):
            raise TypeError(
                f"@tack.func '{func_name}' expects {len(callee_params)} args, "
                f"got {len(call_node.args)}"
            )

        # Create a name renamer for the callee's body
        rename_map = {}
        for param_name in callee_params:
            rename_map[param_name] = self._fresh_name(f"__{func_name}_{param_name}_{suffix}__")

        # Detect return count: 0=void, 1=scalar, >1=tuple
        n_returns = self._detect_return_count(funcdef)
        if n_returns == 0:
            result_var = None
        elif n_returns > 1:
            result_var = [self._fresh_name(f"__{func_name}_ret_{c}_{suffix}__")
                          for c in range(n_returns)]
        else:
            result_var = self._fresh_name(f"__{func_name}_ret_{suffix}__")

        # Rename all local variables in the callee body to avoid collisions
        # We collect all assigned names and create renames for them
        assigned_names = self._collect_assigned_names(funcdef.body)
        for name in sorted(assigned_names):
            if name not in rename_map:
                rename_map[name] = self._fresh_name(f"__{func_name}_{name}_{suffix}__")

        # Override rename map for local array / shared memory params:
        # alias the caller's array name directly so the inlined body
        # accesses it without an assignment (arrays can't be assigned in C).
        # Must happen BEFORE the renamer runs.
        for param_name in callee_params:
            if isinstance(call_node.args[callee_params.index(param_name)], ast.Name):
                arg_name = call_node.args[callee_params.index(param_name)].id
                if arg_name in self._shared_vars:
                    rename_map[param_name] = arg_name

        # Rename the callee AST (deep copy first)
        renamed_body = _structure_returns(copy.deepcopy(funcdef.body), func_name)
        renamer = _NameRenamer(rename_map, result_var)
        # Flatten in case visit_Return returns a list (multi-return)
        flat_body = []
        for stmt in renamed_body:
            result = renamer.visit(stmt)
            if isinstance(result, list):
                flat_body.extend(result)
            else:
                flat_body.append(result)
        renamed_body = flat_body

        # Propagate vector-ness and texture metadata for renamed parameters
        # (must happen before parameter assignments so we can skip texture assigns)
        for param_name in callee_params:
            renamed = rename_map[param_name]
            if isinstance(call_node.args[callee_params.index(param_name)], ast.Name):
                arg_name = call_node.args[callee_params.index(param_name)].id
                if arg_name in self._vector_vars:
                    self._vector_vars[renamed] = self._vector_vars[arg_name]
                if arg_name in self._vector_fields:
                    # A vector field passed in: `fld[i]` in the body must
                    # expand to its components, as it does in the caller.
                    self._vector_fields[renamed] = self._vector_fields[arg_name]
                if arg_name in self._texture_fields:
                    self._texture_fields[renamed] = self._texture_fields[arg_name]
                    self._texture_origin[renamed] = self._texture_origin.get(arg_name, arg_name)

        # Emit parameter assignments
        stmts = []
        for param_name, arg_ast in zip(callee_params, call_node.args):
            renamed = rename_map[param_name]
            # Skip assignment for texture params and local array params —
            # these are aliased to the caller's variable directly.
            if renamed in self._texture_fields:
                continue
            if renamed in self._shared_vars:
                continue
            arg_val = self.visit(arg_ast)
            # Capture any stmts from visiting this arg (e.g. nested inlines)
            stmts.extend(self._pre_stmts)
            self._pre_stmts = []
            if isinstance(arg_val, list):
                # Vector argument — assign each component
                ndim = len(arg_val)
                self._vector_vars[renamed] = ndim
                for c in range(ndim):
                    stmts.append(ir.IRAssign(
                        target=self._component_name(renamed, c), value=arg_val[c]))
            else:
                stmts.append(ir.IRAssign(target=renamed, value=arg_val))

        # Visit the renamed body statements
        if func_obj in self._active_funcs:
            raise NotImplementedError(f"Recursive @tack.func '{func_name}' is not supported")
        caller_bindings = self._call_bindings
        callee_bindings.locals.update(rename_map.values())
        self._call_bindings = callee_bindings
        self._active_funcs.add(func_obj)
        try:
            body_ir = self._visit_body(renamed_body)
        finally:
            self._active_funcs.remove(func_obj)
            self._call_bindings = caller_bindings
        stmts.extend(body_ir)

        # Restore saved pre_stmts and append all inline stmts
        self._pre_stmts = saved_pre_stmts
        self._pre_stmts.extend(stmts)

        # Void function: no return value
        if result_var is None:
            return None

        # Multi-return: return list of IRNames (treated as tuple)
        if isinstance(result_var, list):
            return [ir.IRName(v) for v in result_var]

        # Check if result is a vector
        if result_var in self._vector_vars:
            ndim = self._vector_vars[result_var]
            return [ir.IRName(self._component_name(result_var, c)) for c in range(ndim)]

        return ir.IRName(result_var)

    def _collect_assigned_names(self, stmts) -> set[str]:
        """Collect all variable names assigned in a list of AST statements.

        Every binding counts, including the names inside a tuple target
        (`t, u = f()`, `for i, j in ndrange(...)`): a callee local that is
        not collected is not renamed, and the inlined body then writes
        the caller's variable of the same name.
        """
        names = set()

        def targets(node):
            if isinstance(node, ast.Name):
                names.add(node.id)
            elif isinstance(node, (ast.Tuple, ast.List)):
                for elt in node.elts:
                    targets(elt)

        for stmt in stmts:
            for node in ast.walk(stmt):
                if isinstance(node, ast.Assign):
                    for t in node.targets:
                        targets(t)
                elif isinstance(node, ast.AugAssign):
                    targets(node.target)
                elif isinstance(node, ast.For):
                    targets(node.target)
        return names

    def _detect_return_count(self, funcdef) -> int:
        """Detect if a function returns a tuple (multi-return).

        Returns the number of return values (0 for void, 1 for scalar, >1 for tuple).
        """
        for node in ast.walk(funcdef):
            if isinstance(node, ast.Return) and node.value:
                if isinstance(node.value, ast.Tuple):
                    return len(node.value.elts)
                return 1
        return 0

    # --- Vector operations ---

    def _try_parse_shared_alloc(self, target_name: str, value_node: ast.Call):
        """Try to parse smem = tack.shared(tack.f32, 256). Returns IRSharedAlloc or None."""
        try:
            name = self._resolve_call_name(value_node)
        except (NotImplementedError, AttributeError):
            return None
        if name != "shared":
            return None
        if len(value_node.args) != 2:
            raise NotImplementedError("tack.shared() takes exactly 2 arguments (dtype, size)")

        # Parse dtype argument — tack.f32, tack.i32, etc.
        dtype_arg = value_node.args[0]
        if isinstance(dtype_arg, ast.Attribute):
            dtype_str = dtype_arg.attr
        elif isinstance(dtype_arg, ast.Name):
            dtype_str = dtype_arg.id
        else:
            raise NotImplementedError("tack.shared() dtype must be tack.f32, tack.i32, etc.")

        from tack.lang.types import _NAME_TO_TYPE
        scalar_type = _NAME_TO_TYPE.get(dtype_str)
        if scalar_type is None:
            raise NotImplementedError(f"Unsupported shared memory dtype: {dtype_str}")

        size = self.visit(value_node.args[1])
        self._shared_vars.add(target_name)
        return ir.IRSharedAlloc(name=target_name, dtype=scalar_type, size=size)

    def _try_parse_shared_like(self, target_name: str, value_node: ast.Call):
        """Try to parse smem = tack.shared_like(field, 256). Returns IRSharedAlloc or None."""
        try:
            name = self._resolve_call_name(value_node)
        except (NotImplementedError, AttributeError):
            return None
        if name != "shared_like":
            return None
        if len(value_node.args) != 2:
            raise NotImplementedError("tack.shared_like() takes exactly 2 arguments (field, size)")

        # First arg is the field reference
        field_arg = value_node.args[0]
        if isinstance(field_arg, ast.Name):
            field_name = field_arg.id
        elif isinstance(field_arg, ast.Attribute):
            field_name = field_arg.attr
        else:
            raise NotImplementedError("tack.shared_like() first argument must be a field name")

        size = self.visit(value_node.args[1])
        self._shared_vars.add(target_name)
        return ir.IRSharedAlloc(name=target_name, dtype=None, size=size, field_name=field_name)

    def _try_parse_local_alloc(self, target_name: str, value_node: ast.Call):
        """Try to parse arr = tack.local_array(tack.f32, 8). Returns IRLocalAlloc or None."""
        try:
            name = self._resolve_call_name(value_node)
        except (NotImplementedError, AttributeError):
            return None
        if name != "local_array":
            return None
        if len(value_node.args) != 2:
            raise NotImplementedError("tack.local_array() takes exactly 2 arguments (dtype, size)")

        dtype_arg = value_node.args[0]
        if isinstance(dtype_arg, ast.Attribute):
            dtype_str = dtype_arg.attr
        elif isinstance(dtype_arg, ast.Name):
            dtype_str = dtype_arg.id
        else:
            raise NotImplementedError("tack.local_array() dtype must be tack.f32, tack.i32, etc.")

        from tack.lang.types import _NAME_TO_TYPE
        scalar_type = _NAME_TO_TYPE.get(dtype_str)
        if scalar_type is None:
            raise NotImplementedError(f"Unsupported local array dtype: {dtype_str}")

        size = self.visit(value_node.args[1])
        self._shared_vars.add(target_name)  # treat as array for indexing purposes
        return ir.IRLocalAlloc(name=target_name, dtype=scalar_type, size=size)

    def _try_parse_local_array_like(self, target_name: str, value_node: ast.Call):
        """Try to parse arr = tack.local_array_like(field, 8). Returns IRLocalAlloc or None."""
        try:
            name = self._resolve_call_name(value_node)
        except (NotImplementedError, AttributeError):
            return None
        if name != "local_array_like":
            return None
        if len(value_node.args) != 2:
            raise NotImplementedError("tack.local_array_like() takes exactly 2 arguments (field, size)")

        # First arg is the field reference
        field_arg = value_node.args[0]
        if isinstance(field_arg, ast.Name):
            field_name = field_arg.id
        elif isinstance(field_arg, ast.Attribute):
            field_name = field_arg.attr
        else:
            raise NotImplementedError("tack.local_array_like() first argument must be a field name")

        size = self.visit(value_node.args[1])
        self._shared_vars.add(target_name)  # treat as array for indexing purposes
        return ir.IRLocalAlloc(name=target_name, dtype=None, size=size, field_name=field_name)

    def _try_parse_vector_construct(self, value_node: ast.expr) -> list | None:
        """Try to parse a Vector([a, b, c]) constructor. Returns list of AST element nodes or None."""
        if not isinstance(value_node, ast.Call):
            return None
        try:
            name = self._resolve_call_name(value_node)
        except (NotImplementedError, AttributeError):
            return None
        if name != "Vector":
            return None
        if len(value_node.args) != 1:
            return None
        arg = value_node.args[0]
        if isinstance(arg, ast.List):
            return arg.elts
        return None

    def _visit_vector_construct(self, node: ast.Call):
        """Handle Vector([a, b, c]) → list of IR expressions."""
        if len(node.args) != 1:
            raise NotImplementedError("Vector() takes exactly one argument (a list)")
        arg = node.args[0]
        if not isinstance(arg, ast.List):
            raise NotImplementedError("Vector() argument must be a list literal")
        return self._visit_ordered(arg.elts)

    def _assign_vector(self, name: str, ast_elts: list) -> list:
        """Assign a vector construction to a variable: v = Vector([a, b, c])."""
        return self._assign_vector_from_ir(name, self._visit_ordered(ast_elts))

    def _assign_vector_from_ir(self, name: str, components: list) -> list:
        """Assign a vector expression result to a variable."""
        ndim = len(components)
        self._vector_vars[name] = ndim
        names = [self._component_name(name, c) for c in range(ndim)]
        stmts = []
        components = self._settle_components(components, stmts, names)
        for target, comp in zip(names, components):
            stmts.append(ir.IRAssign(target=target, value=comp))
        return stmts

    def _settle_components(self, components: list, statements: list, targets=None) -> list:
        """Components that can be assigned one at a time, in order.

        A vector assignment lowers to one assignment per component, but its
        right side is a single value that Python evaluates completely before
        binding anything. A component that reads what an earlier component's
        assignment has already written would see the new value, so it is
        evaluated into a temporary first: for a vector variable, a read of
        an earlier target component (``v = v.cross(w)``); for a field
        element, any field load, since fields may share storage
        (``a[i] = a[i].cross(b[i])``). ``targets`` names the variable's
        components, or is None for a store to a field.
        """
        settled = list(components)
        for c in range(1, len(settled)):
            if targets is None:
                hazard = any(isinstance(n, ir.IRFieldLoad) for n in walk_ir(settled[c]))
            else:
                written = set(targets[:c])
                hazard = any(isinstance(n, ir.IRName) and n.name in written
                             for n in walk_ir(settled[c]))
            if hazard:
                settled[c] = self._capture_value(settled[c], statements, freeze_name=True)
        return settled

    def _store_vector_field(self, target: ast.Subscript, components: list) -> list:
        """Store a vector into a vector field: field[i] = vec."""
        field_node, index_node, components = self._visit_store_location(target, components)
        ndim = len(components)
        stmts = []
        # Each component store repeats the index, so one that loads from a
        # field is read before the first store can change it.
        if any(isinstance(n, ir.IRFieldLoad) for n in walk_ir(index_node)):
            index_node = self._capture_value(index_node, stmts)
        int_index = ir.IRCast(value=index_node, dtype=i32)
        components = self._settle_components(components, stmts)
        for c in range(ndim):
            stmts.append(ir.IRFieldStore(
                field=field_node, index=self._component_index(int_index, ndim, c),
                value=components[c]))
        return stmts

    def _component_index(self, element, ndim: int, c: int):
        """Where component ``c`` of element ``element`` is stored: element * ndim + c."""
        return ir.IRBinOp(
            op="+",
            left=ir.IRBinOp(op="*", left=element, right=ir.IRConstant(ndim)),
            right=ir.IRConstant(c),
        )

    def _componentwise(self, node, construct: str, args: list) -> list:
        """Per-component argument lists for a scalar operation given vectors.

        Vector arguments must have one width; scalar arguments are repeated
        for every component.
        """
        widths = sorted({len(a) for a in args if isinstance(a, list)})
        if len(widths) != 1:
            sizes = " and ".join(f"{w}-vector" for w in widths)
            raise self._source_error(node, construct, f"combines a {sizes}")
        return [[a[c] if isinstance(a, list) else a for a in args] for c in range(widths[0])]

    # --- Vector field elements: vf[i] op= vec, vf[i][c] = x, vf[i][c] op= x ---

    def _is_field_component(self, target) -> bool:
        """``vf[i][c]``: one component of an element of a vector field."""
        return (isinstance(target, ast.Subscript) and isinstance(target.value, ast.Subscript)
                and isinstance(target.value.value, ast.Name)
                and target.value.value.id in self._vector_fields)

    def _field_element(self, node: ast.Subscript):
        """The field and the component indices of the vector field element ``vf[i]``.

        The element index is evaluated once, so a load and a store of the
        element can share it.
        """
        ndim = self._vector_fields[node.value.id]
        index = self._capture_value(self._visit_subscript_index(node), self._pre_stmts)
        field = self.visit(node.value)
        element = ir.IRCast(value=index, dtype=i32)
        return field, [self._component_index(element, ndim, c) for c in range(ndim)]

    def _component_stores(self, field, indices: list, selector, value):
        """Store ``value`` to the component of a field element ``selector`` picks."""
        if isinstance(selector, int):
            return ir.IRFieldStore(field=field, index=indices[selector], value=value)
        value = self._capture_value(value, self._pre_stmts)
        return [
            ir.IRIf(ir.IRCompare(op="==", left=selector, right=ir.IRConstant(c)),
                    [ir.IRFieldStore(field=field, index=index, value=value)], [])
            for c, index in enumerate(indices)
        ]

    def _assign_field_component(self, target: ast.Subscript, value):
        """``vf[i][c] = value``.

        A literal component is one store. A runtime one guards a store to
        each component, as for a vector variable: out of range stores
        nothing.
        """
        if isinstance(value, list):
            raise self._source_error(
                target, "assignment", "a component of a vector must be a scalar")
        # The value is evaluated before the target's indices.
        saved = self._pre_stmts
        self._pre_stmts = []
        field, indices = self._field_element(target.value)
        selector = self._component_selector(target, len(indices))
        statements = self._pre_stmts
        self._pre_stmts = saved
        if statements:
            value = self._capture_value(value, self._pre_stmts)
            self._pre_stmts.extend(statements)
        return self._component_stores(field, indices, selector, value)

    def _augment_field_component(self, target: ast.Subscript, op: str, value_node):
        """``vf[i][c] op= value``: indices once, the old value read first."""
        field, indices = self._field_element(target.value)
        selector = self._component_selector(target, len(indices))
        loads = [ir.IRFieldLoad(field=field, index=index) for index in indices]
        if isinstance(selector, int):
            read = loads[selector]
        else:
            read = self._select_component(selector, loads)
        right, statements = self._visit_expression(value_node)
        if isinstance(right, list):
            raise self._source_error(
                target, "augmented assignment", "combines a component of a vector with a vector")
        if statements:
            read = self._capture_value(read, self._pre_stmts)
            self._pre_stmts.extend(statements)
        return self._component_stores(
            field, indices, selector, ir.IRBinOp(op=op, left=read, right=right))

    def _augment_vector_field(self, target: ast.Subscript, op: str, value_node):
        """``vf[i] op= value`` for a vector or a scalar ``value``."""
        field, indices = self._field_element(target)
        loads = [ir.IRFieldLoad(field=field, index=index) for index in indices]
        right, statements = self._visit_expression(value_node)
        if statements:
            loads = self._capture_value(loads, self._pre_stmts)
            self._pre_stmts.extend(statements)
        rows = self._componentwise(target, "augmented assignment", [loads, right])
        stmts = []
        values = self._settle_components(
            [ir.IRBinOp(op=op, left=old, right=new) for old, new in rows], stmts)
        stmts.extend(ir.IRFieldStore(field=field, index=index, value=value)
                     for index, value in zip(indices, values))
        return stmts

    def _visit_as_vector(self, value_node, ndim: int) -> list:
        """Visit an expression and ensure it returns vector components."""
        result = self.visit(value_node)
        if isinstance(result, list):
            if len(result) != ndim:
                raise TypeError(f"Vector dimension mismatch: expected {ndim}, got {len(result)}")
            return result
        # Scalar → broadcast to all components
        return [result] * ndim

    def _try_visit_vector_method(self, node: ast.Call):
        """Try to handle vector method calls: v.normalized(), v.cross(w), etc."""
        if not isinstance(node.func, ast.Attribute):
            return None

        method_name = node.func.attr
        obj_node = node.func.value

        # Check if the object is a known vector variable
        if isinstance(obj_node, ast.Name) and obj_node.id in self._vector_vars:
            vec_name = obj_node.id
            ndim = self._vector_vars[vec_name]
            components = [ir.IRName(self._component_name(vec_name, c)) for c in range(ndim)]
            return self._emit_vector_method(method_name, components, ndim, node.args)

        # Also handle chained expressions: (expr).normalized()
        obj_result = self.visit(obj_node)
        if isinstance(obj_result, list):
            ndim = len(obj_result)
            return self._emit_vector_method(method_name, obj_result, ndim, node.args)

        return None

    def _emit_vector_method(self, method_name: str, components: list, ndim: int, arg_nodes: list):
        """Emit IR for a vector method call."""
        if method_name in ('normalized', 'norm', 'norm_sqr') and arg_nodes:
            raise NotImplementedError(f"{method_name}() takes no arguments")
        if method_name == "normalized":
            # length = sqrt(sum(c*c for c in components))
            sum_sq = components[0]
            sum_sq = ir.IRBinOp(op="*", left=components[0], right=components[0])
            for c in range(1, ndim):
                sum_sq = ir.IRBinOp(op="+", left=sum_sq,
                                    right=ir.IRBinOp(op="*", left=components[c], right=components[c]))
            length = ir.IRCall(func_name="sqrt", args=[sum_sq])
            return [ir.IRBinOp(op="/", left=c, right=length) for c in components]

        if method_name == "norm":
            sum_sq = ir.IRBinOp(op="*", left=components[0], right=components[0])
            for c in range(1, ndim):
                sum_sq = ir.IRBinOp(op="+", left=sum_sq,
                                    right=ir.IRBinOp(op="*", left=components[c], right=components[c]))
            return ir.IRCall(func_name="sqrt", args=[sum_sq])

        if method_name == "norm_sqr":
            sum_sq = ir.IRBinOp(op="*", left=components[0], right=components[0])
            for c in range(1, ndim):
                sum_sq = ir.IRBinOp(op="+", left=sum_sq,
                                    right=ir.IRBinOp(op="*", left=components[c], right=components[c]))
            return sum_sq

        if method_name == "dot":
            if len(arg_nodes) != 1:
                raise TypeError("dot() takes exactly one argument")
            other = self.visit(arg_nodes[0])
            if not isinstance(other, list) or len(other) != ndim:
                raise TypeError("dot() argument must be a vector of same dimension")
            result = ir.IRBinOp(op="*", left=components[0], right=other[0])
            for c in range(1, ndim):
                result = ir.IRBinOp(op="+", left=result,
                                    right=ir.IRBinOp(op="*", left=components[c], right=other[c]))
            return result

        if method_name == "cross":
            if ndim != 3:
                raise TypeError("cross() only defined for 3D vectors")
            if len(arg_nodes) != 1:
                raise TypeError("cross() takes exactly one argument")
            other = self.visit(arg_nodes[0])
            if not isinstance(other, list) or len(other) != 3:
                raise TypeError("cross() argument must be a 3D vector")
            a0, a1, a2 = components
            b0, b1, b2 = other
            return [
                ir.IRBinOp(op="-",
                           left=ir.IRBinOp(op="*", left=a1, right=b2),
                           right=ir.IRBinOp(op="*", left=a2, right=b1)),
                ir.IRBinOp(op="-",
                           left=ir.IRBinOp(op="*", left=a2, right=b0),
                           right=ir.IRBinOp(op="*", left=a0, right=b2)),
                ir.IRBinOp(op="-",
                           left=ir.IRBinOp(op="*", left=a0, right=b1),
                           right=ir.IRBinOp(op="*", left=a1, right=b0)),
            ]

        raise NotImplementedError(f"Vector method '{method_name}' not supported")

    # --- Helpers ---

    def _vector_component(self, node: ast.Subscript, components: list):
        """``components[index]`` as one scalar expression.

        A literal index picks the component at lowering. A runtime index
        selects through a chain of conditional expressions, so the result is
        a scalar wherever a scalar is expected and no local array is needed;
        an index past the last component yields the last component (Python
        would raise, and a kernel cannot). The index is evaluated once.
        """
        selector = self._component_selector(node, len(components))
        if isinstance(selector, int):
            return components[selector]
        return self._select_component(selector, components)

    def _component_selector(self, node: ast.Subscript, n: int):
        """The component a subscript of an n-vector names.

        An ``int`` for a literal index, checked against the width;
        otherwise the index as an IR value, evaluated once.
        """
        index = node.slice
        if isinstance(index, ast.Constant) and isinstance(index.value, int):
            c = index.value
            if not -n <= c < n:
                raise self._source_error(
                    node, "subscript", f"component {c} of a {n}-vector is out of range")
            return c % n
        idx, statements = self._visit_expression(index)
        self._pre_stmts.extend(statements)
        if isinstance(idx, list):
            raise self._source_error(node, "subscript", "a vector cannot index a vector")
        return self._capture_value(idx, self._pre_stmts)

    def _select_component(self, selector, components: list):
        """The component a runtime ``selector`` picks; past the last, the last."""
        result = components[-1]
        for c in range(len(components) - 2, -1, -1):
            result = ir.IRIfExp(
                ir.IRCompare(op="==", left=selector, right=ir.IRConstant(c)),
                components[c], result)
        return result

    def _store_vector_component(self, target: ast.Subscript, value):
        """``v[index] = value`` for a vector variable ``v``.

        A literal index assigns one component. A runtime index guards an
        assignment to each component with a comparison, so exactly the
        selected component changes; out of range changes nothing.
        """
        name = target.value.id
        n = self._vector_vars[name]
        if isinstance(value, list):
            raise self._source_error(
                target, "assignment", "a component of a vector must be a scalar")
        idx = self._component_selector(target, n)
        if isinstance(idx, int):
            return ir.IRAssign(target=self._component_name(name, idx), value=value)
        value = self._capture_value(value, self._pre_stmts)
        return [
            ir.IRIf(ir.IRCompare(op="==", left=idx, right=ir.IRConstant(c)),
                    [ir.IRAssign(target=self._component_name(name, c), value=value)], [])
            for c in range(n)
        ]

    def _visit_store_location(self, target, value):
        """Evaluate an assignment RHS before side effects in its target."""
        saved = self._pre_stmts
        self._pre_stmts = []
        field = self.visit(target.value)
        index = self._visit_subscript_index(target)
        statements = self._pre_stmts
        self._pre_stmts = saved
        if statements:
            value = self._capture_value(value, self._pre_stmts)
            self._pre_stmts.extend(statements)
        return field, index, value

    def _visit_subscript_index(self, node: ast.Subscript):
        """Extract and linearize index from a subscript.

        Handles:
        - field[i] → i
        - field[None] → 0
        - field[i, j] → i * DimSize(field, 1) + j
        - field[i, j, k] → (i * DimSize(field, 1) + j) * DimSize(field, 2) + k
        """
        # field[None] → 0
        if isinstance(node.slice, ast.Constant) and node.slice.value is None:
            return ir.IRConstant(0)

        # Multi-dimensional: field[i, j, k]
        if isinstance(node.slice, ast.Tuple):
            field_name = node.value.id if isinstance(node.value, ast.Name) else None
            if field_name is None:
                raise NotImplementedError("Multi-dim indexing requires a named field")

            return self._linearize_index(node, field_name, self._visit_ordered(node.slice.elts))

        index = self.visit(node.slice)
        if isinstance(index, list):
            # A vector indexes one dimension per component: g[I] is g[I[0], I[1]]
            if not isinstance(node.value, ast.Name):
                raise self._source_error(node, "subscript", "indexes an unnamed field with a vector")
            return self._linearize_index(node, node.value.id, [index])
        return index

    def _linearize_index(self, node, field_name: str, indices: list):
        """Row-major index from one index per dimension: (i * dim1 + j) * dim2 + k.

        A vector among the indices supplies one dimension per component.
        """
        flat = []
        for index in indices:
            flat.extend(index if isinstance(index, list) else [index])
        result = flat[0]
        for d in range(1, len(flat)):
            dim_size = ir.IRDimSize(field_name=field_name, dim=d)
            result = ir.IRBinOp(
                op="+",
                left=ir.IRBinOp(op="*", left=result, right=dim_size),
                right=flat[d],
            )
        return result

    def _is_range_call(self, node: ast.expr) -> bool:
        """Check if an AST node is a call to range()."""
        return (isinstance(node, ast.Call) and
                self._resolve_call_name(node) == 'range')

    def _parse_range_args(self, call_node: ast.Call):
        """Parse range(end), range(start, end), or range(start, end, step)."""
        args = self._visit_ordered(call_node.args)
        if len(args) == 1:
            return ir.IRConstant(0), args[0], None
        if len(args) == 2:
            return args[0], args[1], None
        if len(args) == 3:
            return args[0], args[1], args[2]
        raise NotImplementedError("range() takes 1-3 arguments")

    def _resolve_call_name(self, node: ast.Call) -> str:
        """Resolve the function name from a Call node.

        Handles:
          - bare name: sqrt(x) → "sqrt"
          - module attribute: math.sqrt(x) → "sqrt"
          - tack attribute: tack.sqrt(x) → "sqrt"
        """
        return self._call_bindings.call_name(node.func)

    def _binop_str(self, op: ast.operator) -> str:
        ops = {
            ast.Add: "+",
            ast.Sub: "-",
            ast.Mult: "*",
            ast.Div: "/",
            ast.FloorDiv: "//",
            ast.Mod: "%",
            ast.Pow: "**",
            ast.LShift: "<<",
            ast.RShift: ">>",
            ast.BitOr: "|",
            ast.BitXor: "^",
            ast.BitAnd: "&",
        }
        op_type = type(op)
        if op_type not in ops:
            raise NotImplementedError(f"Unsupported binary operator: {op_type.__name__}")
        return ops[op_type]

    def _unaryop_str(self, op: ast.unaryop) -> str:
        ops = {
            ast.UAdd: "+",
            ast.USub: "-",
            ast.Not: "not",
            ast.Invert: "~",
        }
        op_type = type(op)
        if op_type not in ops:
            raise NotImplementedError(f"Unsupported unary operator: {op_type.__name__}")
        return ops[op_type]

    def _cmpop_str(self, op: ast.cmpop) -> str:
        ops = {
            ast.Eq: "==",
            ast.NotEq: "!=",
            ast.Lt: "<",
            ast.LtE: "<=",
            ast.Gt: ">",
            ast.GtE: ">=",
        }
        op_type = type(op)
        if op_type not in ops:
            raise NotImplementedError(f"Unsupported comparison operator: {op_type.__name__}")
        return ops[op_type]


def _effect_name(node) -> str | None:
    """Name an observable effect, or None for an effect-free node."""
    if isinstance(node, ir.IRFieldStore):
        return "store"
    if isinstance(node, (ir.IRAtomicOp, ir.IRBlockReduce)):
        prefix = "atomic" if isinstance(node, ir.IRAtomicOp) else "block"
        return f"{prefix}_{node.op}()"
    if isinstance(node, ir.IRBarrier):
        return "barrier()"
    if isinstance(node, ir.IRPrint):
        return "print()"
    return None


def _mark_outermost_continues(stmts: list):
    """Flag each `continue` that belongs to the parallel loop itself."""
    for stmt in stmts:
        if isinstance(stmt, ir.IRContinue):
            stmt.outermost = True
        elif isinstance(stmt, ir.IRIf):
            _mark_outermost_continues(stmt.then_body)
            _mark_outermost_continues(stmt.else_body or [])
        # Nested loops own their continues; do not descend into them.


def _has_return(stmts: list) -> bool:
    return any(isinstance(n, ast.Return) for s in stmts for n in ast.walk(s))


def _structure_returns(stmts: list, func_name: str) -> list:
    """Make every `return` the last statement on its path.

    Inlining lowers `return x` to an assignment, which does not leave the
    function: after `if c: return a` the statements that follow would still
    run and overwrite the result. Statements after an `if` that returns are
    moved into its branches, so each path ends at its own return.
    """
    for idx, stmt in enumerate(stmts):
        if isinstance(stmt, ast.Return):
            return stmts[:idx + 1]  # the rest is unreachable
        if isinstance(stmt, (ast.For, ast.While)) and _has_return([stmt]):
            raise NotImplementedError(
                f"@tack.func '{func_name}': 'return' inside a loop is not "
                f"supported. Assign the result to a variable, 'break', and "
                f"return after the loop.")
        if isinstance(stmt, ast.If) and _has_return([stmt]):
            rest = stmts[idx + 1:]
            stmt.body = _structure_returns(
                stmt.body + copy.deepcopy(rest), func_name)
            stmt.orelse = _structure_returns(stmt.orelse + rest, func_name)
            return [*stmts[:idx], stmt]
    return stmts


class _NameRenamer(ast.NodeTransformer):
    """Renames variables in an AST subtree and converts return → assignment.

    result_var can be:
    - str: single return value → one assignment
    - list[str]: multi-return (tuple) → multiple assignments
    """

    def __init__(self, rename_map: dict[str, str], result_var):
        self._rename_map = rename_map
        self._result_var = result_var  # str or list[str]

    def visit_Name(self, node: ast.Name) -> ast.Name:
        if node.id in self._rename_map:
            # Keep the position and the source spelling for diagnostics.
            renamed = ast.copy_location(ast.Name(id=self._rename_map[node.id], ctx=node.ctx), node)
            renamed._source_id = node.id
            return renamed
        return node

    def visit_Return(self, node: ast.Return):
        """Convert 'return expr' → assignment(s).

        Single return: 'return x' → '__func_ret_N__ = x'
        Multi-return:  'return (a, b)' → '__func_ret_0_N__ = a; __func_ret_1_N__ = b'
        """
        value = self.visit(node.value) if node.value else ast.Constant(value=0)

        # Multi-return: result_var is a list, value should be a Tuple
        if isinstance(self._result_var, list):
            if isinstance(value, ast.Tuple):
                stmts = []
                for var, elt in zip(self._result_var, value.elts):
                    stmts.append(ast.copy_location(ast.Assign(
                        targets=[ast.Name(id=var, ctx=ast.Store())],
                        value=elt,
                    ), node))
                return stmts
            # Single expression returned but expected multi — assign to first
            return ast.copy_location(ast.Assign(
                targets=[ast.Name(id=self._result_var[0], ctx=ast.Store())],
                value=value,
            ), node)

        # Keep the return's position for diagnostics in the inlined body.
        return ast.copy_location(ast.Assign(
            targets=[ast.Name(id=self._result_var, ctx=ast.Store())],
            value=value,
        ), node)

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        """Rename function parameters."""
        node = self.generic_visit(node)
        for arg in node.args.args:
            if arg.arg in self._rename_map:
                arg.arg = self._rename_map[arg.arg]
        return node


def transform_kernel(kernel_ast: ast.Module, vector_fields=None,
                     texture_fields=None, python_func=None, bindings=None,
                     template_funcs=None) -> ir.IRModule:
    """Transform a kernel's Python AST into Tack IR.

    Args:
        kernel_ast: Parsed Python AST of the kernel function.
        vector_fields: Optional dict mapping parameter names to their
            vector component count (e.g., {"pixels": 3, "cam_pos": 3}).
        texture_fields: Optional dict mapping parameter names to their
            3D shape (e.g., {"vol": (100, 100, 100)}).
        python_func: Defining Python callable for globals/closure bindings.
        bindings: Explicit namespace for AST-only callers without a callable.
        template_funcs: Transformation-local map of resolved template methods.
    """
    transformer = KernelTransformer(vector_fields=vector_fields,
                                    texture_fields=texture_fields, python_func=python_func,
                                    bindings=bindings, template_funcs=template_funcs)
    return transformer.visit(kernel_ast)
