"""PGC AST transformation — Python AST to PGC IR.

Transforms a @kernel-decorated Python function's AST into PGC's internal IR.
Supports: parallel/sequential for-range loops, while loops, if/else, comparisons,
boolean ops, unary ops, math builtins, field indexing, type inference,
@pgc.func inlining, multi-dimensional indexing, ndrange, and vector operations.

Inspired by Taichi's AST transformer (Apache 2.0), simplified for PGC's needs.
"""

import ast
import copy
import math

from pgc.lang import ir


# Math builtins that map to LLVM intrinsics / libm calls
MATH_BUILTINS = {
    "sqrt", "sin", "cos", "tan",
    "asin", "acos", "atan", "atan2",
    "exp", "log", "log2", "log10",
    "floor", "ceil",
    "abs", "min", "max", "pow",
    "fabs",
    "exp2",
}


class KernelTransformer(ast.NodeVisitor):
    """Transforms a Python AST (from a @kernel function) into PGC IR.

    Tracks nesting depth to distinguish parallel for-loops (top-level)
    from sequential for-loops (nested inside another for-loop).

    Supports:
      - @pgc.func inlining at call sites
      - Multi-dimensional field indexing: field[i, j] → field[i * shape1 + j]
      - field[None] → field[0] for scalar fields
      - ndrange(w, h) → 1D parallel loop with index decomposition
      - Vector scalarization: Vector([a, b, c]) → 3 scalar variables
    """

    def __init__(self, vector_fields=None):
        self._loop_depth = 0
        self._inline_counter = 0  # unique suffix for inlined variables
        # Vector tracking: name → number of components
        self._vector_vars: dict[str, int] = {}
        # Statements generated by expression-level inlining (hoisted before current stmt)
        self._pre_stmts: list = []
        # Vector field metadata: param_name → number of components
        self._vector_fields: dict[str, int] = vector_fields or {}

    def visit_Module(self, node: ast.Module) -> ir.IRModule:
        module = ir.IRModule()
        for stmt in node.body:
            if isinstance(stmt, ast.FunctionDef):
                module.functions.append(self.visit_FunctionDef(stmt))
        return module

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ir.IRFunction:
        params = []
        for arg in node.args.args:
            params.append(ir.IRParam(
                name=arg.arg,
                type_annotation=None,  # resolved during type inference
            ))
        body = self._visit_body(node.body)
        return ir.IRFunction(name=node.name, params=params, body=body)

    def _visit_body(self, stmts: list) -> list:
        """Visit a list of statements, filtering out None results.

        Also collects any pre-statements generated by expression-level
        inlining of @pgc.func calls and inserts them before the statement
        that triggered them.
        """
        result = []
        for stmt in stmts:
            self._pre_stmts = []
            visited = self.visit(stmt)
            # Insert any hoisted inline statements before this statement
            result.extend(self._pre_stmts)
            self._pre_stmts = []
            if visited is not None:
                if isinstance(visited, list):
                    result.extend(visited)
                else:
                    result.append(visited)
        return result

    # --- Loops ---

    def visit_For(self, node: ast.For) -> ir.IRNode:
        target = node.target

        if node.orelse:
            raise NotImplementedError("'else' clause on for-loop not supported in kernels")

        # Handle tuple targets: for i, j in ndrange(w, h)
        if isinstance(target, ast.Tuple):
            return self._visit_ndrange_for(node)

        if not isinstance(target, ast.Name):
            raise NotImplementedError("Only simple loop variables supported")

        # Detect for i in range(...)
        if not self._is_range_call(node.iter):
            raise NotImplementedError("Only range() loops supported in kernels")

        start, end = self._parse_range_args(node.iter)

        self._loop_depth += 1
        body = self._visit_body(node.body)
        self._loop_depth -= 1

        # Top-level for-range is parallel; nested for-range is sequential
        if self._loop_depth == 0:
            return ir.IRParallelFor(var=target.id, start=start, end=end, body=body)
        else:
            return ir.IRSequentialFor(var=target.id, start=start, end=end, body=body)

    def _visit_ndrange_for(self, node: ast.For):
        """Handle: for i, j in ndrange(w, h) or for i, j in pgc.ndrange(w, h)."""
        target = node.target
        if not isinstance(target, ast.Tuple):
            raise NotImplementedError("ndrange requires tuple target")

        names = []
        for elt in target.elts:
            if not isinstance(elt, ast.Name):
                raise NotImplementedError("ndrange targets must be simple names")
            names.append(elt.id)

        # Parse ndrange call
        call = node.iter
        if not isinstance(call, ast.Call):
            raise NotImplementedError("Expected ndrange() call")

        func_name = self._resolve_call_name(call)
        if func_name != "ndrange":
            raise NotImplementedError(f"Expected ndrange(), got {func_name}()")

        if len(call.args) != len(names):
            raise NotImplementedError(
                f"ndrange() dimension count ({len(call.args)}) must match "
                f"target count ({len(names)})"
            )

        dim_exprs = [self.visit(a) for a in call.args]

        # Compute total = dim0 * dim1 * ...
        total = dim_exprs[0]
        for d in dim_exprs[1:]:
            total = ir.IRBinOp(op="*", left=total, right=d)

        # Build body: decompose linear index into multi-dim indices
        # for __nd_idx__ in range(total):
        #     i = __nd_idx__ // dim1
        #     j = __nd_idx__ % dim1
        # For 3D: i = idx // (d1*d2), j = (idx // d2) % d1, k = idx % d2
        idx_name = f"__nd_idx_{self._inline_counter}__"
        self._inline_counter += 1

        decomp_stmts = []
        remaining = ir.IRName(idx_name)

        for k in range(len(names) - 1):
            # Product of remaining dimensions
            tail_product = dim_exprs[k + 1]
            for d in dim_exprs[k + 2:]:
                tail_product = ir.IRBinOp(op="*", left=tail_product, right=d)

            decomp_stmts.append(
                ir.IRAssign(target=names[k],
                            value=ir.IRBinOp(op="//", left=remaining, right=tail_product))
            )
            remaining = ir.IRBinOp(op="%", left=remaining, right=tail_product)

        # Last dimension gets the remainder
        decomp_stmts.append(ir.IRAssign(target=names[-1], value=remaining))

        self._loop_depth += 1
        body_stmts = self._visit_body(node.body)
        self._loop_depth -= 1

        full_body = decomp_stmts + body_stmts

        if self._loop_depth == 0:
            return ir.IRParallelFor(
                var=idx_name, start=ir.IRConstant(0), end=total, body=full_body)
        else:
            return ir.IRSequentialFor(
                var=idx_name, start=ir.IRConstant(0), end=total, body=full_body)

    def visit_While(self, node: ast.While) -> ir.IRWhile:
        if node.orelse:
            raise NotImplementedError("'else' clause on while-loop not supported in kernels")
        condition = self.visit(node.test)
        body = self._visit_body(node.body)
        return ir.IRWhile(condition=condition, body=body)

    def visit_Break(self, node: ast.Break) -> ir.IRBreak:
        return ir.IRBreak()

    def visit_Continue(self, node: ast.Continue) -> ir.IRContinue:
        return ir.IRContinue()

    # --- Control flow ---

    def visit_If(self, node: ast.If) -> ir.IRIf:
        condition = self.visit(node.test)
        then_body = self._visit_body(node.body)
        else_body = self._visit_body(node.orelse)
        return ir.IRIf(condition=condition, then_body=then_body, else_body=else_body)

    def visit_IfExp(self, node: ast.IfExp) -> ir.IRIfExp:
        return ir.IRIfExp(
            condition=self.visit(node.test),
            then_value=self.visit(node.body),
            else_value=self.visit(node.orelse),
        )

    # --- Assignments ---

    def visit_Assign(self, node: ast.Assign) -> ir.IRNode:
        if len(node.targets) != 1:
            raise NotImplementedError("Multiple assignment targets not supported")

        target = node.targets[0]
        value = node.value

        # Tuple unpacking: a, b = expr
        if isinstance(target, ast.Tuple):
            return self._visit_tuple_unpack(target, value)

        # Check for vector construction: v = pgc.Vector([a, b, c])
        vec_elts = self._try_parse_vector_construct(value)
        if vec_elts is not None and isinstance(target, ast.Name):
            return self._assign_vector(target.id, vec_elts)

        visited_value = self.visit(value)

        # Check if RHS is a vector variable → propagate vector-ness
        if isinstance(visited_value, list):
            # Vector expression result (list of IR nodes)
            if isinstance(target, ast.Name):
                return self._assign_vector_from_ir(target.id, visited_value)
            # Vector store: field[i] = vec_var
            if isinstance(target, ast.Subscript):
                return self._store_vector_field(target, visited_value)

        # field[i] = expr  →  IRFieldStore
        if isinstance(target, ast.Subscript):
            field = self.visit(target.value)
            index = self._visit_subscript_index(target)
            return ir.IRFieldStore(field=field, index=index, value=visited_value)

        # x = expr  →  IRAssign
        if isinstance(target, ast.Name):
            # Clear vector tracking if reassigning to scalar
            self._vector_vars.pop(target.id, None)
            return ir.IRAssign(target=target.id, value=visited_value)

        raise NotImplementedError(f"Unsupported assignment target: {type(target).__name__}")

    def visit_AugAssign(self, node: ast.AugAssign) -> ir.IRNode:
        target = node.target
        op = self._binop_str(node.op)

        # Check for vector augmented assignment: v += w
        if isinstance(target, ast.Name) and target.id in self._vector_vars:
            ndim = self._vector_vars[target.id]
            rhs_components = self._visit_as_vector(node.value, ndim)
            stmts = []
            for c in range(ndim):
                lhs = ir.IRName(f"{target.id}__{c}")
                rhs = ir.IRBinOp(op=op, left=lhs, right=rhs_components[c])
                stmts.append(ir.IRAssign(target=f"{target.id}__{c}", value=rhs))
            return stmts

        rhs = ir.IRBinOp(op=op, left=self.visit(target), right=self.visit(node.value))

        if isinstance(target, ast.Subscript):
            field = self.visit(target.value)
            index = self._visit_subscript_index(target)
            return ir.IRFieldStore(field=field, index=index, value=rhs)

        if isinstance(target, ast.Name):
            return ir.IRAssign(target=target.id, value=rhs)

        raise NotImplementedError("Unsupported augmented assignment target")

    def visit_Return(self, node: ast.Return) -> ir.IRReturn:
        value = self.visit(node.value) if node.value else None
        return ir.IRReturn(value=value)

    def _visit_tuple_unpack(self, target: ast.Tuple, value_node: ast.expr) -> list:
        """Handle tuple unpacking: a, b = expr."""
        names = []
        for elt in target.elts:
            if not isinstance(elt, ast.Name):
                raise NotImplementedError("Only simple names in tuple unpacking")
            names.append(elt.id)
        n = len(names)

        # Tuple literal RHS: a, b = b, a (need temps for correct swap)
        if isinstance(value_node, ast.Tuple):
            if len(value_node.elts) != n:
                raise TypeError(
                    f"Tuple unpacking: expected {n} values, got {len(value_node.elts)}")
            stmts = []
            temps = []
            for i, elt in enumerate(value_node.elts):
                tmp = f"__unpack_tmp_{self._inline_counter}_{i}__"
                val = self.visit(elt)
                if isinstance(val, list):
                    ndim = len(val)
                    self._vector_vars[tmp] = ndim
                    for c, comp in enumerate(val):
                        stmts.append(ir.IRAssign(target=f"{tmp}__{c}", value=comp))
                    temps.append(('vector', tmp, ndim))
                else:
                    stmts.append(ir.IRAssign(target=tmp, value=val))
                    temps.append(('scalar', tmp, None))
            self._inline_counter += 1
            # Assign temps to targets
            for name, (kind, tmp, ndim) in zip(names, temps):
                if kind == 'vector':
                    self._vector_vars[name] = ndim
                    for c in range(ndim):
                        stmts.append(ir.IRAssign(
                            target=f"{name}__{c}", value=ir.IRName(f"{tmp}__{c}")))
                else:
                    self._vector_vars.pop(name, None)
                    stmts.append(ir.IRAssign(target=name, value=ir.IRName(tmp)))
            return stmts

        # Expression RHS (e.g., multi-return from @pgc.func)
        visited_value = self.visit(value_node)

        if isinstance(visited_value, list):
            if len(visited_value) != n:
                raise TypeError(
                    f"Tuple unpacking: expected {n} values, got {len(visited_value)}")
            stmts = []
            for name, val in zip(names, visited_value):
                self._vector_vars.pop(name, None)
                stmts.append(ir.IRAssign(target=name, value=val))
            return stmts

        raise NotImplementedError("Cannot unpack non-tuple value")

    # --- Expressions ---

    def visit_BinOp(self, node: ast.BinOp) -> ir.IRNode:
        op = self._binop_str(node.op)
        left = self.visit(node.left)
        right = self.visit(node.right)

        # Vector-scalar or vector-vector binary ops
        left_is_vec = isinstance(left, list)
        right_is_vec = isinstance(right, list)

        if left_is_vec or right_is_vec:
            if left_is_vec and right_is_vec:
                if len(left) != len(right):
                    raise TypeError("Vector dimension mismatch in binary op")
                return [ir.IRBinOp(op=op, left=l, right=r) for l, r in zip(left, right)]
            elif left_is_vec:
                return [ir.IRBinOp(op=op, left=l, right=right) for l in left]
            else:
                return [ir.IRBinOp(op=op, left=left, right=r) for r in right]

        return ir.IRBinOp(op=op, left=left, right=right)

    def visit_UnaryOp(self, node: ast.UnaryOp) -> ir.IRNode:
        op = self._unaryop_str(node.op)
        operand = self.visit(node.operand)

        if isinstance(operand, list):
            return [ir.IRUnaryOp(op=op, operand=c) for c in operand]

        return ir.IRUnaryOp(op=op, operand=operand)

    def visit_Compare(self, node: ast.Compare) -> ir.IRNode:
        # Desugar chained comparisons: a < b < c  →  (a < b) and (b < c)
        comparisons = []
        left = self.visit(node.left)
        for op_node, comparator in zip(node.ops, node.comparators):
            right = self.visit(comparator)
            op = self._cmpop_str(op_node)
            comparisons.append(ir.IRCompare(op=op, left=left, right=right))
            left = right

        if len(comparisons) == 1:
            return comparisons[0]
        return ir.IRBoolOp(op="and", values=comparisons)

    def visit_BoolOp(self, node: ast.BoolOp) -> ir.IRBoolOp:
        op = "and" if isinstance(node.op, ast.And) else "or"
        values = [self.visit(v) for v in node.values]
        return ir.IRBoolOp(op=op, values=values)

    def visit_Subscript(self, node: ast.Subscript) -> ir.IRNode:
        # Check for vector component access: v[0], v[1], v[2]
        if isinstance(node.value, ast.Name) and node.value.id in self._vector_vars:
            if isinstance(node.slice, ast.Constant) and isinstance(node.slice.value, int):
                comp = node.slice.value
                return ir.IRName(f"{node.value.id}__{comp}")

        # Get field name for vector field detection
        field_name = node.value.id if isinstance(node.value, ast.Name) else None
        is_vector_field = field_name is not None and field_name in self._vector_fields

        # Compute the linearized index (handles multi-dim, None, etc.)
        index = self._visit_subscript_index(node)
        field_ir = self.visit(node.value)

        # Vector field load: expand to n component loads
        if is_vector_field:
            ndim = self._vector_fields[field_name]
            result = []
            for c in range(ndim):
                comp_idx = ir.IRBinOp(
                    op="+",
                    left=ir.IRBinOp(op="*", left=index, right=ir.IRConstant(ndim)),
                    right=ir.IRConstant(c),
                )
                result.append(ir.IRFieldLoad(field=field_ir, index=comp_idx))
            return result

        return ir.IRFieldLoad(field=field_ir, index=index)

    def visit_Attribute(self, node: ast.Attribute) -> ir.IRAttribute:
        return ir.IRAttribute(
            obj=self.visit(node.value),
            attr=node.attr,
        )

    def visit_Name(self, node: ast.Name) -> ir.IRNode:
        # If this name is a vector variable, return its components as a list
        if node.id in self._vector_vars:
            ndim = self._vector_vars[node.id]
            return [ir.IRName(f"{node.id}__{c}") for c in range(ndim)]
        return ir.IRName(name=node.id)

    def visit_Constant(self, node: ast.Constant) -> ir.IRConstant:
        return ir.IRConstant(value=node.value)

    def visit_Tuple(self, node: ast.Tuple) -> list:
        """Visit tuple — used for multi-dimensional indexing like field[i, j]."""
        return [self.visit(elt) for elt in node.elts]

    def visit_Call(self, node: ast.Call) -> ir.IRNode:
        func_name = self._resolve_call_name(node)

        # Check for @pgc.func calls → inline
        from pgc.lang.func import _func_registry
        if func_name in _func_registry:
            return self._inline_func_call(func_name, node)

        # Vector constructor: Vector([a, b, c]) or pgc.Vector([a, b, c])
        if func_name == "Vector":
            return self._visit_vector_construct(node)

        # Math builtins from the math module or bare names
        if func_name in MATH_BUILTINS:
            args = [self.visit(arg) for arg in node.args]
            return ir.IRCall(func_name=func_name, args=args)

        # len(field) → attribute access to shape
        if func_name == "len":
            if len(node.args) != 1:
                raise NotImplementedError("len() takes exactly one argument")
            arg = self.visit(node.args[0])
            return ir.IRAttribute(obj=arg, attr="__len__")

        # range() is handled in visit_For; if it appears elsewhere, error
        if func_name == "range":
            raise NotImplementedError("range() outside of for-loop not supported")

        # ndrange() outside of for-loop
        if func_name == "ndrange":
            raise NotImplementedError("ndrange() outside of for-loop not supported")

        # int(), float() type casts
        if func_name in ("int", "float"):
            if len(node.args) != 1:
                raise NotImplementedError(f"{func_name}() takes exactly one argument")
            return ir.IRCast(value=self.visit(node.args[0]), dtype=func_name)

        # Check for vector method calls: v.normalized(), v.cross(w), v.dot(w), v.norm()
        if isinstance(node.func, ast.Attribute):
            obj_result = self._try_visit_vector_method(node)
            if obj_result is not None:
                return obj_result

        raise NotImplementedError(f"Function call '{func_name}' not supported in kernels")

    def visit_Expr(self, node: ast.Expr) -> ir.IRNode:
        """Expression statement (e.g., standalone function call)."""
        # Skip docstrings and other standalone string constants
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            return None
        return self.visit(node.value)

    # --- @pgc.func inlining ---

    def _inline_func_call(self, func_name: str, call_node: ast.Call):
        """Inline a @pgc.func call at the call site.

        Produces a list of IR statements (parameter assignments + body),
        and returns the result variable name as an IRName.
        """
        from pgc.lang.func import _func_registry

        func_obj = _func_registry[func_name]
        funcdef = func_obj._funcdef

        # Save and reset _pre_stmts so nested inlining doesn't interfere
        saved_pre_stmts = self._pre_stmts
        self._pre_stmts = []

        # Unique suffix to avoid name collisions across multiple inlines
        suffix = self._inline_counter
        self._inline_counter += 1

        # Map callee params to caller args
        callee_params = [a.arg for a in funcdef.args.args]
        if len(call_node.args) != len(callee_params):
            raise TypeError(
                f"@pgc.func '{func_name}' expects {len(callee_params)} args, "
                f"got {len(call_node.args)}"
            )

        # Create a name renamer for the callee's body
        rename_map = {}
        for param_name in callee_params:
            rename_map[param_name] = f"__{func_name}_{param_name}_{suffix}__"

        # Detect multi-return: does the func return a tuple?
        n_returns = self._detect_return_count(funcdef)
        if n_returns > 1:
            result_var = [f"__{func_name}_ret_{c}_{suffix}__" for c in range(n_returns)]
        else:
            result_var = f"__{func_name}_ret_{suffix}__"

        # Rename all local variables in the callee body to avoid collisions
        # We collect all assigned names and create renames for them
        assigned_names = self._collect_assigned_names(funcdef.body)
        for name in assigned_names:
            if name not in rename_map:
                rename_map[name] = f"__{func_name}_{name}_{suffix}__"

        # Rename the callee AST (deep copy first)
        renamed_body = copy.deepcopy(funcdef.body)
        renamer = _NameRenamer(rename_map, result_var)
        # Flatten in case visit_Return returns a list (multi-return)
        flat_body = []
        for stmt in renamed_body:
            result = renamer.visit(stmt)
            if isinstance(result, list):
                flat_body.extend(result)
            else:
                flat_body.append(result)
        renamed_body = flat_body

        # Emit parameter assignments
        stmts = []
        for param_name, arg_ast in zip(callee_params, call_node.args):
            renamed = rename_map[param_name]
            arg_val = self.visit(arg_ast)
            # Capture any stmts from visiting this arg (e.g. nested inlines)
            stmts.extend(self._pre_stmts)
            self._pre_stmts = []
            if isinstance(arg_val, list):
                # Vector argument — assign each component
                ndim = len(arg_val)
                self._vector_vars[renamed] = ndim
                for c in range(ndim):
                    stmts.append(ir.IRAssign(target=f"{renamed}__{c}", value=arg_val[c]))
            else:
                stmts.append(ir.IRAssign(target=renamed, value=arg_val))

        # Also propagate vector-ness for renamed parameters
        for param_name in callee_params:
            renamed = rename_map[param_name]
            # Check if the corresponding arg is a vector in the caller
            if isinstance(call_node.args[callee_params.index(param_name)], ast.Name):
                arg_name = call_node.args[callee_params.index(param_name)].id
                if arg_name in self._vector_vars:
                    self._vector_vars[renamed] = self._vector_vars[arg_name]

        # Visit the renamed body statements
        body_ir = self._visit_body(renamed_body)
        stmts.extend(body_ir)

        # Restore saved pre_stmts and append all inline stmts
        self._pre_stmts = saved_pre_stmts
        self._pre_stmts.extend(stmts)

        # Multi-return: return list of IRNames (treated as tuple)
        if isinstance(result_var, list):
            return [ir.IRName(v) for v in result_var]

        # Check if result is a vector
        if result_var in self._vector_vars:
            ndim = self._vector_vars[result_var]
            return [ir.IRName(f"{result_var}__{c}") for c in range(ndim)]

        return ir.IRName(result_var)

    def _collect_assigned_names(self, stmts) -> set[str]:
        """Collect all variable names assigned in a list of AST statements."""
        names = set()
        for stmt in stmts:
            for node in ast.walk(stmt):
                if isinstance(node, ast.Assign):
                    for t in node.targets:
                        if isinstance(t, ast.Name):
                            names.add(t.id)
                elif isinstance(node, ast.AugAssign):
                    if isinstance(node.target, ast.Name):
                        names.add(node.target.id)
                elif isinstance(node, ast.For):
                    if isinstance(node.target, ast.Name):
                        names.add(node.target.id)
        return names

    def _detect_return_count(self, funcdef) -> int:
        """Detect if a function returns a tuple (multi-return).

        Returns the number of return values (1 for scalar, >1 for tuple).
        """
        for node in ast.walk(funcdef):
            if isinstance(node, ast.Return) and node.value:
                if isinstance(node.value, ast.Tuple):
                    return len(node.value.elts)
        return 1

    # --- Vector operations ---

    def _try_parse_vector_construct(self, value_node: ast.expr) -> list | None:
        """Try to parse a Vector([a, b, c]) constructor. Returns list of AST element nodes or None."""
        if not isinstance(value_node, ast.Call):
            return None
        try:
            name = self._resolve_call_name(value_node)
        except (NotImplementedError, AttributeError):
            return None
        if name != "Vector":
            return None
        if len(value_node.args) != 1:
            return None
        arg = value_node.args[0]
        if isinstance(arg, ast.List):
            return arg.elts
        return None

    def _visit_vector_construct(self, node: ast.Call):
        """Handle Vector([a, b, c]) → list of IR expressions."""
        if len(node.args) != 1:
            raise NotImplementedError("Vector() takes exactly one argument (a list)")
        arg = node.args[0]
        if not isinstance(arg, ast.List):
            raise NotImplementedError("Vector() argument must be a list literal")
        return [self.visit(elt) for elt in arg.elts]

    def _assign_vector(self, name: str, ast_elts: list) -> list:
        """Assign a vector construction to a variable: v = Vector([a, b, c])."""
        ndim = len(ast_elts)
        self._vector_vars[name] = ndim
        stmts = []
        for c, elt in enumerate(ast_elts):
            val = self.visit(elt)
            stmts.append(ir.IRAssign(target=f"{name}__{c}", value=val))
        return stmts

    def _assign_vector_from_ir(self, name: str, components: list) -> list:
        """Assign a vector expression result to a variable."""
        ndim = len(components)
        self._vector_vars[name] = ndim
        stmts = []
        for c, comp in enumerate(components):
            stmts.append(ir.IRAssign(target=f"{name}__{c}", value=comp))
        return stmts

    def _store_vector_field(self, target: ast.Subscript, components: list) -> list:
        """Store a vector into a vector field: field[i] = vec."""
        field_node = self.visit(target.value)
        index_node = self._visit_subscript_index(target)
        ndim = len(components)
        stmts = []
        for c in range(ndim):
            # field[i * ndim + c]
            actual_index = ir.IRBinOp(
                op="+",
                left=ir.IRBinOp(op="*", left=index_node, right=ir.IRConstant(ndim)),
                right=ir.IRConstant(c),
            )
            stmts.append(ir.IRFieldStore(field=field_node, index=actual_index, value=components[c]))
        return stmts

    def _visit_as_vector(self, value_node, ndim: int) -> list:
        """Visit an expression and ensure it returns vector components."""
        result = self.visit(value_node)
        if isinstance(result, list):
            if len(result) != ndim:
                raise TypeError(f"Vector dimension mismatch: expected {ndim}, got {len(result)}")
            return result
        # Scalar → broadcast to all components
        return [result] * ndim

    def _try_visit_vector_method(self, node: ast.Call):
        """Try to handle vector method calls: v.normalized(), v.cross(w), etc."""
        if not isinstance(node.func, ast.Attribute):
            return None

        method_name = node.func.attr
        obj_node = node.func.value

        # Check if the object is a known vector variable
        if isinstance(obj_node, ast.Name) and obj_node.id in self._vector_vars:
            vec_name = obj_node.id
            ndim = self._vector_vars[vec_name]
            components = [ir.IRName(f"{vec_name}__{c}") for c in range(ndim)]
            return self._emit_vector_method(method_name, components, ndim, node.args)

        # Also handle chained expressions: (expr).normalized()
        obj_result = self.visit(obj_node)
        if isinstance(obj_result, list):
            ndim = len(obj_result)
            return self._emit_vector_method(method_name, obj_result, ndim, node.args)

        return None

    def _emit_vector_method(self, method_name: str, components: list, ndim: int, arg_nodes: list):
        """Emit IR for a vector method call."""
        if method_name == "normalized":
            # length = sqrt(sum(c*c for c in components))
            sum_sq = components[0]
            sum_sq = ir.IRBinOp(op="*", left=components[0], right=components[0])
            for c in range(1, ndim):
                sum_sq = ir.IRBinOp(op="+", left=sum_sq,
                                    right=ir.IRBinOp(op="*", left=components[c], right=components[c]))
            length = ir.IRCall(func_name="sqrt", args=[sum_sq])
            return [ir.IRBinOp(op="/", left=c, right=length) for c in components]

        if method_name == "norm":
            sum_sq = ir.IRBinOp(op="*", left=components[0], right=components[0])
            for c in range(1, ndim):
                sum_sq = ir.IRBinOp(op="+", left=sum_sq,
                                    right=ir.IRBinOp(op="*", left=components[c], right=components[c]))
            return ir.IRCall(func_name="sqrt", args=[sum_sq])

        if method_name == "norm_sqr":
            sum_sq = ir.IRBinOp(op="*", left=components[0], right=components[0])
            for c in range(1, ndim):
                sum_sq = ir.IRBinOp(op="+", left=sum_sq,
                                    right=ir.IRBinOp(op="*", left=components[c], right=components[c]))
            return sum_sq

        if method_name == "dot":
            if len(arg_nodes) != 1:
                raise TypeError("dot() takes exactly one argument")
            other = self.visit(arg_nodes[0])
            if not isinstance(other, list) or len(other) != ndim:
                raise TypeError("dot() argument must be a vector of same dimension")
            result = ir.IRBinOp(op="*", left=components[0], right=other[0])
            for c in range(1, ndim):
                result = ir.IRBinOp(op="+", left=result,
                                    right=ir.IRBinOp(op="*", left=components[c], right=other[c]))
            return result

        if method_name == "cross":
            if ndim != 3:
                raise TypeError("cross() only defined for 3D vectors")
            if len(arg_nodes) != 1:
                raise TypeError("cross() takes exactly one argument")
            other = self.visit(arg_nodes[0])
            if not isinstance(other, list) or len(other) != 3:
                raise TypeError("cross() argument must be a 3D vector")
            a0, a1, a2 = components
            b0, b1, b2 = other
            return [
                ir.IRBinOp(op="-",
                           left=ir.IRBinOp(op="*", left=a1, right=b2),
                           right=ir.IRBinOp(op="*", left=a2, right=b1)),
                ir.IRBinOp(op="-",
                           left=ir.IRBinOp(op="*", left=a2, right=b0),
                           right=ir.IRBinOp(op="*", left=a0, right=b2)),
                ir.IRBinOp(op="-",
                           left=ir.IRBinOp(op="*", left=a0, right=b1),
                           right=ir.IRBinOp(op="*", left=a1, right=b0)),
            ]

        raise NotImplementedError(f"Vector method '{method_name}' not supported")

    # --- Helpers ---

    def _visit_subscript_index(self, node: ast.Subscript):
        """Extract and linearize index from a subscript.

        Handles:
        - field[i] → i
        - field[None] → 0
        - field[i, j] → i * DimSize(field, 1) + j
        - field[i, j, k] → (i * DimSize(field, 1) + j) * DimSize(field, 2) + k
        """
        # field[None] → 0
        if isinstance(node.slice, ast.Constant) and node.slice.value is None:
            return ir.IRConstant(0)

        # Multi-dimensional: field[i, j, k]
        if isinstance(node.slice, ast.Tuple):
            field_name = node.value.id if isinstance(node.value, ast.Name) else None
            if field_name is None:
                raise NotImplementedError("Multi-dim indexing requires a named field")

            indices = [self.visit(elt) for elt in node.slice.elts]

            # Linearize: (i * dim1 + j) * dim2 + k
            result = indices[0]
            for d in range(1, len(indices)):
                dim_size = ir.IRDimSize(field_name=field_name, dim=d)
                result = ir.IRBinOp(
                    op="+",
                    left=ir.IRBinOp(op="*", left=result, right=dim_size),
                    right=indices[d],
                )
            return result

        return self.visit(node.slice)

    def _is_range_call(self, node: ast.expr) -> bool:
        """Check if an AST node is a call to range()."""
        return (isinstance(node, ast.Call) and
                isinstance(node.func, ast.Name) and
                node.func.id == "range")

    def _parse_range_args(self, call_node: ast.Call):
        """Parse range(end) or range(start, end) call arguments."""
        args = call_node.args
        if len(args) == 1:
            return ir.IRConstant(0), self.visit(args[0])
        elif len(args) == 2:
            return self.visit(args[0]), self.visit(args[1])
        else:
            raise NotImplementedError("range() with step not yet supported")

    def _resolve_call_name(self, node: ast.Call) -> str:
        """Resolve the function name from a Call node.

        Handles:
          - bare name: sqrt(x) → "sqrt"
          - module attribute: math.sqrt(x) → "sqrt"
          - pgc attribute: pgc.sqrt(x) → "sqrt"
        """
        func = node.func
        if isinstance(func, ast.Name):
            return func.id
        if isinstance(func, ast.Attribute):
            # math.sqrt, pgc.sqrt → just "sqrt"
            return func.attr
        raise NotImplementedError(f"Unsupported function call syntax: {ast.dump(func)}")

    def _binop_str(self, op: ast.operator) -> str:
        ops = {
            ast.Add: "+",
            ast.Sub: "-",
            ast.Mult: "*",
            ast.Div: "/",
            ast.FloorDiv: "//",
            ast.Mod: "%",
            ast.Pow: "**",
            ast.LShift: "<<",
            ast.RShift: ">>",
            ast.BitOr: "|",
            ast.BitXor: "^",
            ast.BitAnd: "&",
        }
        op_type = type(op)
        if op_type not in ops:
            raise NotImplementedError(f"Unsupported binary operator: {op_type.__name__}")
        return ops[op_type]

    def _unaryop_str(self, op: ast.unaryop) -> str:
        ops = {
            ast.UAdd: "+",
            ast.USub: "-",
            ast.Not: "not",
            ast.Invert: "~",
        }
        op_type = type(op)
        if op_type not in ops:
            raise NotImplementedError(f"Unsupported unary operator: {op_type.__name__}")
        return ops[op_type]

    def _cmpop_str(self, op: ast.cmpop) -> str:
        ops = {
            ast.Eq: "==",
            ast.NotEq: "!=",
            ast.Lt: "<",
            ast.LtE: "<=",
            ast.Gt: ">",
            ast.GtE: ">=",
        }
        op_type = type(op)
        if op_type not in ops:
            raise NotImplementedError(f"Unsupported comparison operator: {op_type.__name__}")
        return ops[op_type]


class _NameRenamer(ast.NodeTransformer):
    """Renames variables in an AST subtree and converts return → assignment.

    result_var can be:
    - str: single return value → one assignment
    - list[str]: multi-return (tuple) → multiple assignments
    """

    def __init__(self, rename_map: dict[str, str], result_var):
        self._rename_map = rename_map
        self._result_var = result_var  # str or list[str]

    def visit_Name(self, node: ast.Name) -> ast.Name:
        if node.id in self._rename_map:
            return ast.Name(id=self._rename_map[node.id], ctx=node.ctx)
        return node

    def visit_Return(self, node: ast.Return):
        """Convert 'return expr' → assignment(s).

        Single return: 'return x' → '__func_ret_N__ = x'
        Multi-return:  'return (a, b)' → '__func_ret_0_N__ = a; __func_ret_1_N__ = b'
        """
        value = self.visit(node.value) if node.value else ast.Constant(value=0)

        # Multi-return: result_var is a list, value should be a Tuple
        if isinstance(self._result_var, list):
            if isinstance(value, ast.Tuple):
                stmts = []
                for var, elt in zip(self._result_var, value.elts):
                    stmts.append(ast.Assign(
                        targets=[ast.Name(id=var, ctx=ast.Store())],
                        value=elt,
                    ))
                return stmts
            # Single expression returned but expected multi — assign to first
            return ast.Assign(
                targets=[ast.Name(id=self._result_var[0], ctx=ast.Store())],
                value=value,
            )

        return ast.Assign(
            targets=[ast.Name(id=self._result_var, ctx=ast.Store())],
            value=value,
        )

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        """Rename function parameters."""
        node = self.generic_visit(node)
        for arg in node.args.args:
            if arg.arg in self._rename_map:
                arg.arg = self._rename_map[arg.arg]
        return node


def transform_kernel(kernel_ast: ast.Module, vector_fields=None) -> ir.IRModule:
    """Transform a kernel's Python AST into PGC IR.

    Args:
        kernel_ast: Parsed Python AST of the kernel function.
        vector_fields: Optional dict mapping parameter names to their
            vector component count (e.g., {"pixels": 3, "cam_pos": 3}).
    """
    transformer = KernelTransformer(vector_fields=vector_fields)
    return transformer.visit(kernel_ast)
